### ISSUE TITLE
Stacked Realmstones getting deleted

### ISSUE THREAD

**Issue by DeathWalkerX** [Tslat/Advent-Of-Ascension#1129]
When I combined the Worn Book with the first Realmstone, i got a stack of 23 realmstones.
Then i logged off, but when i logged back in the stack was reduced to just 1 Realmstone.
I assume it's because realmstones aren't meant to be stackable.

**Comment by masterbobli** [comment]
Also, using the stack to kill a husk will only return 1; similar things happen when use them on a mineralization station.




On 01/21/2020 15:02, DeathWalkerX wrote:

When I combined the Worn Book with the first Realmstone, i got a stack of 23 realmstones.
Then i logged off, but when i logged back in the stack was reduced to just 1 Realmstone.
I assume it's because realmstones aren't meant to be stackable.

**Comment by Tslat** [comment]
Resolved in 3.2.2
