### ISSUE TITLE
The GUI is very small and hard to see!

### ISSUE THREAD

**Issue by StringKe** [Tslat/Advent-Of-Ascension#1176]
**Mod Version**
What version of the mod are you on?
3.2.3

**Describe the bug**
The GUI is very small and hard to see
**To Reproduce**
1. ESC
2. Options
3. Video Settings
4. GUI Scale:Normal
5. Window Max Size (Resolution: 1920*1080)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31089228/73380494-1b47b780-42ff-11ea-9a58-88cb95a6fab6.png)

**Comment by Tslat** [comment]
You GUI scale in the settings is likely set to small. That causes it to render small.

**Comment by StringKe** [comment]
> You GUI scale in the settings is likely set to small. That causes it to render small.

AOA GUI should scale automatically, not fixed

**Comment by Tslat** [comment]
I have no idea what you'd be looking for here.

The GUI _does_ scale automatically with MC.. that's why it's small here in the first place.
If you don't want a small GUI, don't put the GUI scale on small?


It affects Vanilla in the exact same way
![image](https://user-images.githubusercontent.com/7098525/73531023-5663fb00-4465-11ea-8ade-6177573a2cac.png)

**Comment by Tslat** [comment]
Got a normal scale pic as well in unicode english
![image](https://user-images.githubusercontent.com/7098525/73531465-3e40ab80-4466-11ea-85b5-a45827bf01e6.png)

The issue is that Minecraft's unicode renderer renders text 1-pixel in width, and requires higher scales to allow for full-width pixel rendering.

When you use unicode scaling then scale the gui down, you start to hit the game's limits. You'll see this in small scale, but in normal you're right on the cusp of what MC can handle.

The issue here is that AoA requires more detailed info to be fit in a smaller area, so text had to get slightly smaller. Because scaling already puts the text renderer at its limit, it falls apart when you do it.

There's nothing I can really do here, the only way to fix this is to increase the text size, but then I wouldn't be able to fit the info in the GUI.

**Comment by Kagaribi172** [comment]
Smooth font mod may solve this issue.
