### ISSUE TITLE
Crash with mobs trying to apply potion effects to fake players

### ISSUE THREAD

**Issue by Cynosphere** [Tslat/Advent-Of-Ascension#1239]
**Mod Version**
3.2.3

**Describe the bug**
Mobs that give potion effects to players when attacked (in this case the Night Watcher) crash when trying to give them to fake players when they attack (in this case Industrial Foregoing's Mob Crusher)

**To Reproduce**
1. Setup something that can kill mobs automatically (in this case Industrial Foregoing's Mob Crusher)
2. Have a Night Watcher (or any other mob that puts effects on the player) enter its killing range
3. Have the mob killer attack it

**Expected behavior**
Mob takes damage/dies without a crash happening

**Comment by Tslat** [comment]
Take this issue to that mod.

If their entity isn't capable of handling potions, they should be disabling potion application on them

**Comment by Cynosphere** [comment]
![:>](https://totallynotavir.us/i/m6dmeall.png)

**Comment by Tslat** [comment]
Provide a crash report

**Comment by Cynosphere** [comment]
https://gist.github.com/Cynosphere/47ea15e290b50ad1ff68051ea4c591ed

**Comment by Tslat** [comment]
Yeah there's nothing I can do about that as far as I can tell. I'm checking if the class is the right class, and it is. It's not my fault they're failing to override the relevant methods to prevent crashing on a non-standard entity.

If they're unwilling to do anything about it, it won't be fixed.
If they're 100% sure it's my fault, I'm gonna need them to tell me where they think it's my fault because as far as I can see it's out of my hands
