### ISSUE TITLE
My case for why 3.2 was a downgrade for looting

### ISSUE THREAD

**Issue by GedYT** [Tslat/Advent-Of-Ascension#1286]
A couple disclaimers:

- **I, in no way, shape, or form am trying to minimize the hard work that went into this most recent update. Regardless if I disagree with the design decisions or not, it was a good update, filled with plenty of QoL changes that everyone can appreciate.**

- **I've been playing this mod since back when Xolova (or however you spell it) was actively updating it. This mod has come a long way from the fragmented state it used to be in, and the reason I bring this up was to hopefully provide some credibility along with my upcoming claims, so I don't appear to be uneducated on the mod.**

I strongly believe that this most recent update has turned the looting aspect of this mod into a far less engaging experience.

Right now, the loot tables are dimension-based components. Not actual loot drops, like we had before. For example, AoA mobs from the Overworld have a list of components they can drop with varying chances. Simple things, like coal, scrap, etc.

This promotes the gameplay loop of:

- Arrive in a dimension
- Kill anything AoA until you get the components you need
- Craft whatever it is you're going for.

I think there is a few core psychological reasons that this gameplay loop is hardly exciting. The first one being that depending on the rate at which you gather components, you can build a subconscious expectation **before** you actually meet the component requirements for piece of gear. You can roughly estimate the amount of work and time you will need to put in to receive your reward, and you can make an educated decision whether or not you are willing to commit that time and effort into your reward. At this point, you know that if you grind it, you will receive your reward.

This is where the issues begins. Before you even have the loot, you are already being desensitized to the idea of receiving your loot. Previously, there was a surprise factor to looting, and that is the reason I was engaged.

In prior versions of AoA. It wasn't really possible to predict when you'd be receiving your loot. You didn't know how much time it would take, or effort.

My favorite example (and experience) of AoA was farming for the old Tommy Gun. Specifically because it had a low drop rate. Psychologically, each Sabretooth I killed was an independent event, that yielded the chance of receiving my reward, and that's what drove me to seeking out another chance at it.

It's the same psychology that goes into gambling addictions. Gamblers believe that each hand, or spin is an independent event, not influenced by their previous interactions. This is technically true. Every shot you take you have a chance to strike big, and it's the core reason that drives the gambler (or in this case, the player) to continue engaging in the game.

Also another crucial element to exciting looting that 3.1 delivered was the constant subjection to failure. Now this sounds silly to anyone trying to get a piece of loot, because who would want to fail at getting their loot? But the rush that someone experiences when receiving a rare drop isn't from the drop chance of said item, it's the journey they had to experience to get the that point. Anyone screaming at a piece of loot in excitement undoubtedly had to try and fail 10, 20, 30, **1000** times before getting it. That rush wouldn't exist if you got everything you wanted, or was at least given an estimate of when you'd get it, and that's how 3.2 is structured.

Of course, RNG is still a factor, but it doesn't sit right with me. When someone sees me with a piece of gear, it should be indicative of the journey, the struggle I went through to get that. Or on the flipside, it can be symbolic of how lucky I was in that instance. Which are both things to be proud of in a looter.

Hopefully this post is comprehensive, but my fingers are tired. I don't necessarily believe that 3.2's looting system is all bad. Certainly towards the beginning of a game you shouldn't be tossed into a RNG-check-fest. Perhaps the reasonable request would be to ask to have some of that old incredibly punishing RNG with immediate rewards tied to it back into the game.

**Comment by Tslat** [comment]
I appreciate the feedback - and before I begin I'd like to clarify that regardless of your intent, constructive feedback is always welcome.

Obviously being the originator of the whole premise of the loot update I will be biased in its existence, so I can see the inherent problem with me discussing it. That being said, I do think you've actually missed or misunderstood several key components of how the loot update works.

You mentioned that the way drops work is based on a per-world function. This is actually mostly untrue. Mobs themselves have individual drops which form the basis of the entire system. the dimension-based loot is specific to a couple items at most, and usually they're generic enough that they play a minor role in the overall gameplay itself. 

Basically to give you quick rundown, here's a basic frame of how the system works:

1. Most mobs have a 'material' drop (or several). These drops are based on the entity's aesthetics, function, and lore. This was done so that you can have an ingrained expectation of what you could get from a given mob without having to do any research to find out for sure. You know that a robot type mob is likely to drop some metallic resources, maybe some armour plating, some scrap metal, etc.
2. ALL mobs _additionally_ call to the world-specific table to roll. These table contain world-specific items, such as lottoman tokens, a dimension-specific crafting material, and some misc resources such as seeds or similar.
3. ALL world tables _additionally_ call to the **rare table** This table is rarely called, with much more valuable loot, with many of the most valuable items being extremely rare. Some of the drops we're looking at fractions of a fraction of a percent chance to drop.
4. ALL bosses have several unique full-drops, usually consisting of some weapons, or weapons and armour. These drops are uncommon (usually around a 30% chance to get any item from a given kill). On top of this they also have an extensive supplies table that they drop alongside their rares, usually containing semi-precious resources such as food, potions, minerals, tokens, etc.
5. Various hunter mobs have their own unique drop tables which drop various resource-type drops, OR a specific unique item. These unique item drops _are_ very uncommon, going right back to the couple % chance to obtain like the old days.

The combination of these factors achieves a few things:

1. Those who want consistent, reliable drops get it in the form of material and resource drops.
2. Those who want unique item drops that aren't super rare get it in the form of boss drops.
3. Those who want the rare, grind-intensive drops get it in the form of hunter mob drops.
4. Those who want the extremely-rare, super lucky unique drops get it in the form of the rare table.

I designed this system specifically to cover every base, so that every person would come away with something they can enjoy. The basis of this seems to cover your complaint entirely, assuming I'm understanding it correctly.

From what I can tell, your argument is that you prefer the more grind-intensive, one-off rewarding aspect to loot. The kind of thing where you really work your way towards a drop and when you finally get it you're elated. From my perspective, you get this. Hunter creatures specifically retain this function to cater to people like yourself. On top of this, the rare table also caters to this, and in an even more specific way to you. No-one can expect rare drops due to their rarity and unreliability, but when you get one you really feel lucky and rewarded. I have seen and felt this from watching the community engage with 3.2 and I'm very happy with how the overall system has turned out.

The bottom line to this reply is that while I appreciate your feedback, I do think you are actually missing key information as to how the entire system works, and the specific suggestion you're making already exists. For example:

- Soul Spark ~3.3% chance to drop from Luxocron
- Nethengeic Armour ~4.3% chance to drop from Nethengeic Beasts
- Gardener ~0.05% chance to drop from farming crops
- Utopian Armour ~5.9% chance to drop from Treasure Boxes
- Colour Cannon ~0.12% chance to drop from rare table. (Works out to be 0.06% chance to drop from any given mob kill, not farmable with grinders)

Please correct me if you think I have misinterpreted your suggestion, and I'm still happy to work with whatever you think may be missing.

**Comment by GedYT** [comment]
I appreciate the response - unfortunately for me, a lot of topics you covered I do have my opinions on, but I felt my post begin to sprout already into so many directions that I chose to only hyper-focus on my main point. Consider this my part 2, using your response as a guidance tool to ensure I cover everything.

I will say, I am aware of mob specific tables, world tables, and rare tables. I didn't go in depth on those, and simplified how loot works for the sake of making a point that didn't require the understanding of those tables. I was merely suggesting that while it's cool to collect materials, I didn't believe that specific system of collecting **parts** of something to then create it later is as engaging as the old system, and I gave the reasons as to **why that is**.

I do believe it's crucial to give everything potential to drop something beneficial to the player. It allows for every mob to serve a purpose without directly allowing the player to power creep. In 3.1, some mobs were better off ignored entirely due to the lack of a system like you've implemented. I didn't comment on the rare table, but I believe it's a fantastic approach to the old system. The concept of how the Color Cannon is obtained is absolutely flawless, but that one is unique, and is not an example of how the majority of loot is currently handled.

The part where my issues lies is having the collection of materials take over the majority of the looting system. The materials, in my opinion, should compliment the gameplay, through upgrades, or boss spawners (I know that's already the case; good job), or stimulating the in-game economy. Something that can give the incentive to take a break from power creeping to explore the potential benefit of mob grinding.

I believe the approach to boss loot was excellent. It got pretty mundane farming a boss 4-5 times, getting ALL the drops, and having no other incentive to fight a specific boss, unless I wanted to DPS check it. The boss loot was handled well, and is one of the reasons I continue to play.

I will admit, I was very familiar with Hunter mobs last update, and I was happy with them. I've avoided them this update, not really for any reason, just wanted to try some other things. After reading your response, I'll give them another go.

I see where you're coming from, and certainly mass appeal is the intelligent route to take when it comes to creating **any** piece of content on the internet, but the current system is heavily one-sided on the gameplay loop I illustrated in my opening post. The game **does** undeniably cover my specific taste of a looter, but dis-proportionally. A majority of the gear obtainable requires the 3-step formula to get, which is objectively inferior on a psychological basis specifically when dealing with audience retention. 

and lastly, just a small side note. I completed the W-801 Easter Egg today, and I hope to see more of that in the future, that was incredibly well done, and engaging.

**Comment by Tslat** [comment]
The problem is - you're asking for an infeasible system.

The reason that the majority of the system is based around parts is because having the majority of creatures drop unique items like the old system isn't possible, it's just too many unique items.

There is no way to allow this level of engagement with your intended method of delivery.

Additionally, you do still seem to have missed the point of the hunter mobs, maybe through lack of engagement with them since 3.2.

The old system is still very much present in hunter mobs, bosses, and a few other things (guardians/elder guardians drop biogenic armour for example)

**Comment by GedYT** [comment]
Now I'm confused, the old system is the one I'm requesting. It's hardly 'infeasible' if it's actively been done before, on a satisfactory scale.

I am also advocating for the 3.2 'parts' system to fill in the gaps that 3.1 had, instead of taking over the majority of the looting system.

I also only mentioned Hunter mobs, when I was expressing how I haven't played around with them yet. I never suggested anything was wrong with them, or that anything should change.

I never claimed the old system wasn't present, I know it is, but it's undeniably in the shadow of the new system, which I believe to be a lesser system, and I'm sure you know why at this point.

**Comment by Tslat** [comment]
What if I told you that the 'gaps' that you're requesting 3.2 fill make up the majority of the mod?

**Comment by GedYT** [comment]
That's exactly what I just said, and that's a problem. 3.1 had a great system, but a consequence of that system was that gaps were left by choice. Some mobs were useless.

The 3.2 looting system **belongs** in those gaps, **not** overhauling the majority of looting, which is the direction you took.

You took a a direction that allowed for everything in the mod to play a role; to have a purpose at the **cost** of a satisfactory looting system.

I've noticed a consistent misconception, where you believe that I'm not aware of how you've structured your mod, or maybe how certain systems work. I do. I'm extremely knowledgeable of nearly all aspects of the mod, and how they work. You continue to try to inform me of things I already know, and I feel that's leaving this **mostly** unproductive. I'm also convinced you're failing to understand what it is I'm suggesting here.

For example you've claimed the system I'm requesting isn't possible to create, which that's simply false. The only situation where I could see a response like that formed is you simply are not understanding me, or simply disagreeing for the sake of disagreement.

I really don't have much more to say, I've articulated my point, all other information regarding my case can be found above. You're welcome to ignore the feedback, or create a constructive solution regarding the the psychological downgrades you've implemented to squash a different issue.

I appreciate you taking the time, nonetheless.

**Comment by Immortallis1** [comment]
The majority of people didn't find the 3.1 system great, and find 3.2 an upgrade. Not everybody is willing to spend hours killing mobs to get one single item, especially when only one mob drops the thing and there are eight other mobs taking up the spawn slots. As an example, I spent like three hours killing lost souls to get Shyrelands realmstone in 3.1 and it was absolutely nasty, and it was far from the only nasty thing.

**Comment by Immortallis1** [comment]
The majority of people didn't find the 3.1 system great, and find 3.2 an upgrade. Not everybody is willing to spend hours killing mobs to get one single item, especially when only one mob drops the thing and there are eight other mobs taking up the spawn slots.

As an example, I spent several hours killing lost souls to get Shyrelands realmstone in 3.1 and it was absolutely nasty, and it was far from the only nasty thing. The relief I felt from getting that realmstone paled in comparison to spending hours trying to fight off all sorts of mobs that I knew would never drop it. The same applies for almost any weapon in 3.1 and before

**Comment by Tslat** [comment]
I mean the only thing I can really deduce from everything so far is that you're advocating for the mod to not improve?

Whether you throw around the word 'objectively' or not, your premise is outright false. Game design and psychological addiction theory states that the best results come from gradually reinforced play. Having a single drop that's 2% isn't 'objectively' better than lesser, more common drops sprinkled with more valuable rarer ones. In fact according to modern psych, it's the exact opposite. As we understand it currently, the latter is 'objectively' better.

Here's a quick article going over different types of addictive reward schemes and their pros/cons:
https://www.psychestudy.com/behavioral/learning-memory/operant-conditioning/reinforcement-punishment/partial-reinforcement

On top of this, the system you're requesting is not impossible because it's simply not doable, it's impossible because it doesn't allow for any expansion in the mod going forward. I can't _do_ anything with the mod if all I ever do is just add another item that drops at 2% chance.

**Comment by GedYT** [comment]
Not sure why I'm getting emails about this 13 days later, but if that were the case, and I'm actively advocating for the mod **not to improve** I would encourage the path you've chosen.

Again, I never said a system is objectively better, that is entirely subjective, and this is the reason I closed this topic. You're claiming I said something that I never once claimed, implied, or even believe.

Whatever system you prefer is entirely 100% subjective. What is not up for debate is the **objective** reality that 3.1's system (Which is still present in 3.2 on a significantly smaller scale) does not allow you to build an expectation, and desensitize yourself to the drop **before** it even drops.

If given a crafting recipe, you immediately understand the prerequisites, and begin building an estimate of when you'll be receiving it. That simple situation completely and utterly removes any amount of excitement possible from the situation, and is the reason that 3.1's system was **objectively** more engaging when dealing with those specific metrics.

If each event is an independent event, there is an incentive NOT to abandon the event, due to the time investment already so far. You know that if you leave, you are wasting the time invested with nothing to show.

Regardless, I know that most of what I'm saying is going to be misunderstood, or misconstrued, so I won't waste anymore of my time. The 3.2 system did fill gaps that were in need of attention, kudos to that, but it did cost the quality of the looting system due to unfortunate decisions along the way.

I'm assuming that you're going to continue down this path of regression, good luck in your journey.
