### ISSUE TITLE
God Buff Change.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#130]
God buffs are a neat concept but a lot of the time they end up being to overpowered. So Instead of how about custom made buff for the dimension that fit balance.

For example, Erebron, Instead of giving strength, now gives "Erebrons Breath" (best name I could come up with.)  Pretty much its strength but only increase attack by 50% instead of strength's 100%+.

So all of them will have there own special buff that are just half of what there respective buffs are right now.

**Comment by Cruuk** [comment]
You... do know that strength is very different now than it was in 1.7.10.... right? We have talked about about strength gives +3 raw damage per level rather than 130% damage now many times... and you never saw these discussions once...?

Besides that, certain effects like Selyan's effect will become underpowered. Resistance 1 is 20% resistance, 10% is pretty... small. How would Pluton's haste 3 boost work? Haste 1.5? That ain't right. (Besides, I'm pretty sure it's gonna get changed from Haste to Luck or something).

Sorry, this one isn't too good, but I'll give you this, I've been wanting the god effects to be their own effects as well, mainly so that we can do other things with them besides just the vanilla effect.

**Comment by Sagisolar** [comment]
Ooof
