### ISSUE TITLE
The new Energy and Soul banners should replace the retro banners as drops

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#135]
**Describe/name the existing feature this suggestion relates to**
Both versions of the Energy and Soul banners.

**Describe the change or feature you think would be good to see**
Somewhere back in 2.4.B, newer versions of the Energy and Soul banners, along with a Creation banner were added... with no way of obtaining them, and mobs still drop the retro versions.

The newer versions should replace the retro ones as mob drops. It simply makes no sense for the retro ones to be some of the first banners you get, considering that they have outdated icons and whatnot.

The retro versions can still be kept around, but as easter eggs. Maybe they could rarely be found as part of a ruined teleporter? I dunno

**Include any additional background information**
Maybe the Creation banner could be dropped by any minion that's killed by a non-player mob?

**Comment by Immortallis1** [comment]
In Tslat 1.1.3 the new ones have names "Energy2" "Soul2" and "Creation2" maybe those can be "fixed" as well? Since this is a whole rewrite those could just be "Energy" for instance and the old ones could be "EnergyRetro" or something.

Note that there is no original Creation banner so Creation2 is misleading.

**Comment by Tslat** [comment]
Banner obtaining has changed since this suggestion and this is no longer relevant
