### ISSUE TITLE
Letter to the new developer

### ISSUE THREAD

**Issue by asagami69** [Tslat/Advent-Of-Ascension#1350]
Hey, fellow Neverminers! About half a month ago, I learned that someone had picked up porting this wonderful mod after the original creator left for bigger, better endeavors. I immediately got to playing this, and spent hours on end reading through all the new changes and the update plans. And let me start by saying "Thank you" to the new developer for all his hard work! However, there are several issues that I feel currently need to addressed before the mod really begins to shine.

First off, please update to 1.15 soon. During my brief time on the AoA discord, I saw someone say "we do not plan to update to 1.15 soon" or something along those lines. That's a real disapopintment because all of my favorite mods are on that version and it's really sad to see that AoA is lagging behind in a long-outdated relic. I try to play 1.12 but it's just not the same without being able to throw tridents or stop pillager raids. Even Twilight Forest is attempting to update now, so why are we still in 1.12? I really don't see how this can be anything besides laziness.

If you are going to stay on 1.12, then you might as well add information about 1.7.10 to the wiki. I don't know why you would stay on 1.12, really, but I do know that Orespawn is still on 1.7.10 and it's easily one of the best and most popular mods of all time. As a result, 1.7.10 AoA is relevant and  must be supported on the wiki unless a 1.15 port of Orespawn is made.

Second, please revert to the old system of mob drops that was present before the "Loot Update". It was better because each item felt like something truly special; now that you can craft them, it all feels like another chore. I've almost quit a few times out of boredom due to the loot system making what I get all too predictable.

Also, you should cancel the "Mod Compability Update". Nobody cares about tinkers construct, I asked all my friends and none of them use it. This update is a waste of time and will take time off of what really matters, like new dimensions.

By the way, the next update should be the one that adds Ethereus and Playtopia and all the other ones, since I kind of got bored of all the other dimensions for some reason. After that, there's several dimensions that Xolova was planning to add before he quit that I really feel you should add someday. Although I'd really like you to add all 52 so we can complete Xolova's vision of the perfect Minecraft mod, I understand if you feel that's too much for you, so I selected some which stand out to me in particular:

-The Bazaar
-Davengard
-Eldercarne Chambers
-Lunar Plane
-Crawlodus
-Xax
-Outpost-X
-Eternal Isle
-Silentia
-Vampyros
-The Blackwood
-Selyanica
-Luxonica
-Erebonia
-Plutonia
-Krasaun's Cavern
-Arc of Ascension

As for content for those dimensions, I have loads of unique gun ideas that would make all of them worth visiting. Here are a couple of them - I actually have a long list that I've been composing in school instead of paying attention to my teacher, but I feel like I should just write the best ones here:

-Krasaun's Dawn: Okay, I know this was in before, but why was it removed? The wiki's removed features page (by the way, I really dislike how this is so large. Why is there so much removed content?) said that you didn't want to balance it. That's just lazy, and Krasaun is a centerpiece of the mod's extensive lore. There's no reason not to have a weapon for him, especially when the other gods have sticklers. And speaking of god weapons, please add the claymores back too, I thought their sprites looked cool and that claymores in general were unique.

-Centipede Cannon: Launches giant centipedes at mobs. Aside from doing lots of damage, these inflict poison on hit. You can find it in Crawlodus.

-Eternal Blaster: 99% chance not to consume ammunition! I left the 1% for balancing purposes.

Speaking of the guns, you should return to the old art style used by Xolova; to be blunt, I am not a fan of the new artist's art as it lacks Xolova's trademark style. You really should find someone better to make new textures for you going forward.

Thanks again, and I look forward to seeing Playtopia soon!
-asagami69

**Comment by Cruuk** [comment]
Ah, that's what that name means

**Comment by EatingSilencer** [comment]
I'm going  to address this piece by piece.

> First off, please update to 1.15 soon. During my brief time on the AoA discord, I saw someone say "we do not plan to update to 1.15 soon" or something along those lines. That's a real disapopintment because all of my favorite mods are on that version and it's really sad to see that AoA is lagging behind in a long-outdated relic. I try to play 1.12 but it's just not the same without being able to throw tridents or stop pillager raids. Even Twilight Forest is attempting to update now, so why are we still in 1.12? I really don't see how this can be anything besides laziness.

This is a huge mod. Updating to 1.12.2 took like 7-8 months within itself. Updating to 1.15 probably would not be any different. And by the time 1.15 is out, 1.16 will be out, etc. Will you want the mod to be updated to 1.16 once its out? Scimiguy won't be able to catch up if he's porting the mod all the time, especially if mojang is releasing updates as fast as they are. Now, granted,, once the mod gets to 1.15, 1.15 -> 1.16 may or may not be that big a jump but it is hard to say.

Also, from my understanding most mods are still on 1.12.2. Which mods of yours are porting forward already (besides twilight forest).


> If you are going to stay on 1.12, then you might as well add information about 1.7.10 to the wiki. I don't know why you would stay on 1.12, really, but I do know that Orespawn is still on 1.7.10 and it's easily one of the best and most popular mods of all time. As a result, 1.7.10 AoA is relevant and must be supported on the wiki unless a 1.15 port of Orespawn is made.

I would honestly love it if 1.7.10 information was more easily accessible for players who are stuck because they can't update. This isn't a priority though, though we might be able to implement this in history sections. It won't be the main focus though, as 1.7.10 isn't supported anymore by the mod developer.

I do have an idea for how this could work (scroll down to the bottom to read the idea).

> Second, please revert to the old system of mob drops that was present before the "Loot Update". It was better because each item felt like something truly special; now that you can craft them, it all feels like another chore. I've almost quit a few times out of boredom due to the loot system making what I get all too predictable.

Feedback like this is always good, uuh I guess if you want you can stay on 1.7.10 if you don't like the loot? Especially since you don't seem to be a 1.12.2 fan, and orespawn is only on 1.7.10.


> Also, you should cancel the "Mod Compability Update". Nobody cares about tinkers construct, I asked all my friends and none of them use it. This update is a waste of time and will take time off of what really matters, like new dimensions.

Will comment on this in the below post.

> By the way, the next update should be the one that adds Ethereus and Playtopia and all the other ones, since I kind of got bored of all the other dimensions for some reason. After that, there's several dimensions that Xolova was planning to add before he quit that I really feel you should add someday. Although I'd really like you to add all 52 so we can complete Xolova's vision of the perfect Minecraft mod, I understand if you feel that's too much for you, so I selected some which stand out to me in particular:
> 
> -The Bazaar
> -Davengard
> -Eldercarne Chambers
> -Lunar Plane
> -Crawlodus
> -Xax
> -Outpost-X
> -Eternal Isle
> -Silentia
> -Vampyros
> -The Blackwood
> -Selyanica
> -Luxonica
> -Erebonia
> -Plutonia
> -Krasaun's Cavern
> -Arc of Ascension

Wait a second...how did you get access to all the dimensions. I thought they were deleted off the wiki. Anyway, the non-2.5 snapshot dimensions won't be added because they lack substance - xolova never really made anything for them besides a name and a concept. Even Xolova himself agrees that scimiguy shouldn't do them.

Also, have you considered why the dimensions made you bored? It is possible that the dimensions lack content, and that lack has made you bored. But don't worry, scimiguy is going to update the mod and add new content to the existing dimensions.

> As for content for those dimensions, I have loads of unique gun ideas that would make all of them worth visiting. Here are a couple of them - I actually have a long list that I've been composing in school instead of paying attention to my teacher, but I feel like I should just write the best ones here:
> 
> -Krasaun's Dawn: Okay, I know this was in before, but why was it removed? The wiki's removed features page (by the way, I really dislike how this is so large. Why is there so much removed content?) said that you didn't want to balance it. That's just lazy, and Krasaun is a centerpiece of the mod's extensive lore. There's no reason not to have a weapon for him, especially when the other gods have sticklers. And speaking of god weapons, please add the claymores back too, I thought their sprites looked cool and that claymores in general were unique.

I think being hard to balance was one thing, but I think scimiguy said the way it was programmed didn't work with the new way guns were coded. Also, all of Xolova's lore was scrapped.

The claymores, if they are added, probably won't have the same textures do to issues....
 
> -Centipede Cannon: Launches giant centipedes at mobs. Aside from doing lots of damage, these inflict poison on hit. You can find it in Crawlodus.
> 
> -Eternal Blaster: 99% chance not to consume ammunition! I left the 1% for balancing purposes.

No comment.

> Speaking of the guns, you should return to the old art style used by Xolova; to be blunt, I am not a fan of the new artist's art as it lacks Xolova's trademark style. You really should find someone better to make new textures for you going forward.

I can't speak for the style, but I will say the textures were changed for a good reason.

> Thanks again, and I look forward to seeing Playtopia soon!
> -asagami69
-----
Now that that is out of the way, here is my idea for the wiki:

We will scrap all rules we have right now and replace them with a "Constitution". This Constitution will be divided into a preamble, 7 articles, and 27 ammendments. The structure is as follows:
Preamble - basic intro: this wiki is by the people, for the people, by the people, and for corporations.

Article 1 - establishes the administrators of the wiki. These are people who can delete pages and block users. They make all the decisions and if you disagree with them, nothing happens.

Article 2 - Establishes Scimiguy as surpreme ruler of the wiki and can dictate any changes. Also, by default no mentioning of 2.5 snapshot dimensions outside of feature pages.

Article 3-7 - let's skip these for now.

Amendment 1-27: basically says what you can and can't edit.

So these new rules will basically allow 1.7.10 information in history sections, and will allow 1.7.2 as well. 

The Constitution outlines a new admin signup process, Translate the following code and follow the instructions to become an admin: 

> 01101000 01110100 01110100 01110000 01110011 00111010 00101111 00101111 01110111 01110111 01110111 00101110 01111001 01101111 01110101 01110100 01110101 01100010 01100101 00101110 01100011 01101111 01101101 00101111 01110111 01100001 01110100 01100011 01101000 00111111 01110110 00111101 01100100 01010001 01110111 00110100 01110111 00111001 01010111 01100111 01011000 01100011 01010001

**Comment by asagami69** [comment]
> This is a huge mod. Updating to 1.12.2 took like 7-8 months within itself. Updating to 1.15 probably would not be any different. And by the time 1.15 is out, 1.16 will be out, etc. Will you want the mod to be updated to 1.16 once its out? Scimiguy won't be able to catch up if he's porting the mod all the time, especially if mojang is releasing updates as fast as they are. Now, granted,, once the mod gets to 1.15, 1.15 -> 1.16 may or may not be that big a jump but it is hard to say.

Yes, I will. Scimiguy should hire a large group of people to help him port the mod, since it's important that he both updates it and adds content.

> Also, from my understanding most mods are still on 1.12.2. Which mods of yours are porting forward already (besides twilight forest).

Botania is another big one that is porting forward.

> I would honestly love it if 1.7.10 information was more easily accessible for players who are stuck because they can't update. This isn't a priority though, though we might be able to implement this in history sections. It won't be the main focus though, as 1.7.10 isn't supported anymore by the mod developer.

> Feedback like this is always good, uuh I guess if you want you can stay on 1.7.10 if you don't like the loot? Especially since you don't seem to be a 1.12.2 fan, and orespawn is only on 1.7.10.

But 1.7.10 is missing out on 1.15.2 features. I understand the importance of moving to a "later" version, but I decided my like for 1.15.2 outstrips my like for Orespawn just a little bit.

> Will comment on this in the below post.

Still waiting.

> Wait a second...how did you get access to all the dimensions. I thought they were deleted off the wiki. Anyway, the non-2.5 snapshot dimensions won't be added because they lack substance - xolova never really made anything for them besides a name and a concept. Even Xolova himself agrees that scimiguy shouldn't do them.

I remembered the list by heart the moment it was put on the wiki just in case someone decided to delete them. And I hate to disagree with Xolova but in this case I feel like I know what is better for the mod than either he or Scimiguy do.

> Also, have you considered why the dimensions made you bored? It is possible that the dimensions lack content, and that lack has made you bored. But don't worry, scimiguy is going to update the mod and add new content to the existing dimensions.

Yes, now that I think about it I got bored because they lack ores and guns. I'll be happy if he adds another 2 ores and 10 guns to every dimension within Nevermine.

> As for content for those dimensions, I have loads of unique gun ideas that would make all of them worth visiting. Here are a couple of them - I actually have a long list that I've been composing in school instead of paying attention to my teacher, but I feel like I should just write the best ones here:
> > -Krasaun's Dawn: Okay, I know this was in before, but why was it removed? The wiki's removed features page (by the way, I really dislike how this is so large. Why is there so much removed content?) said that you didn't want to balance it. That's just lazy, and Krasaun is a centerpiece of the mod's extensive lore. There's no reason not to have a weapon for him, especially when the other gods have sticklers. And speaking of god weapons, please add the claymores back too, I thought their sprites looked cool and that claymores in general were unique.
> 
> I think being hard to balance was one thing, but I think scimiguy said the way it was programmed didn't work with the new way guns were coded. Also, all of Xolova's lore was scrapped.

Wait WHAAAT? Xolova's lore was one of the three main reasons I was drawn to this mod to begin with! Now he is just trampling on AoA and turning it into some sort of malformed pale imitation.

> The claymores, if they are added, probably won't have the same textures do to issues....

Why not?

> No comment.

Good to see you realized I have some unique ideas up my sleeve.

> I can't speak for the style, but I will say the textures were changed for a good reason.

Sure they were.
