### ISSUE TITLE
Bosses 

### ISSUE THREAD

**Issue by MagicMaxcer** [Tslat/Advent-Of-Ascension#1358]
**Describe the new feature you think would be good to add**
Bosses can inflict a special effect which nullifies the players potion effects regardless of enchantment of the equipment making the equipment using the base stat. If the player can build blocks to get around the boss projectile bosses are able to shoot through walls. Gravitate the player towards the boss. Bosses can cause the player to drop their equipment randomly. Melee bosses can stun the player unable to move/interact/attack, they can nullify projectile when its attacked by a projectile. A potion effect that can pierce through enchantment and armor. A potion effect that can cause the player damage/attack to be 0 making throwing items and staves worth using. A potion effect that can cause regen to inflict damage instead of healing. These potion effects are for certain bosses or other mobs. 

**Add any alternative implementations you think might work**
The player is cheap if we can think of a way to beat a boss easily thats how we'll do it so why not make the boss be able too beat the player?

**Include any additional background information**
sounds like a lot of coding

**Comment by Ivandagiant** [comment]
I agree- fighting certain bosses is very underwhelming when you can stand a couple blocks above them and just hit them. Smash and Rockrider for instance should be able to pull the player into them, and maybe have a mechanic where they can charge through blocks. Allow them to leap.

Corallus used to be one of my favorite boss fights because it was hard to cheese him since he spawned at a random time and you couldn't choose exactly where he spawned. Now you can make a small room and spawn him in there and just farm him.

Also, I think bosses should have a rapid regen effect if they don't detect that a player is in range. You can just sit far back with a sniper and be in no danger at all currently.

**Comment by Immortallis1** [comment]
> Corallus used to be one of my favorite boss fights because it was hard to cheese him since he spawned at a random time and you couldn't choose exactly where he spawned. Now you can make a small room and spawn him in there and just farm him.

I mean, you don't have to make the small room and cheese the bosses if you don't want to. The fact that the option to do so is there does not stop you from fighting Corallus normally, and the fight itself has not changed.
