### ISSUE TITLE
Versions 3.2.x crash immediately due to FluidsRegister issue

### ISSUE THREAD

**Issue by 0ct0ber** [Tslat/Advent-Of-Ascension#1363]
Version 3.2 and above seems to be broken due to a problem in FluidsRegister/CandiedWaterBlock initialization. Only version 3.1.x and below are playable due to this issue.

Stack trace: https://pastebin.com/EVMRFFd7

Fix to the issue:

This issue is occurring because when FluidsRegister is loaded, it tries to set the candiedWater field to a new CandiedWaterBlock, but the making of CandiedWaterBlock refers to the FluidsRegister.candiedWater variable (which is not yet initialized). This could be fixed by adding a second constructor which does not refer to the variable.

**Comment by Tslat** [comment]
No, you didn't. If anything you CREATED a recursive loop.
I'm closing this PR since you seem unwilling to actually cooperate.

Feel free to provide a full crash report & log when you're ready

**Comment by 0ct0ber** [comment]
@Tslat You're not being very nice... have you tried running **any version** of your own mod since January 17th? I'm not going to reveal my real life name due to the filenames in my log, just run the mod yourself. Feel free to listen when you're ready.

public class FluidsRegister {

    public static final CandiedWaterBlock candiedWater = new CandiedWaterBlock();

}

```
public class CandiedWaterBlock extends BasicFluidBlock {
    public CandiedWaterBlock() {
        super("CandiedWater", FluidsRegister.candiedWater, Material.WATER, MapColor.PINK);
        //candiedWater is final and has not been initialized yet. It is essentially as bad as running super("CandiedWater", this, Material.Water, MapColor.PINK);. And you left this bug in there since January 17th.
    }
```

**Comment by Tslat** [comment]
I run the version myself whenever I play, and by the looks of things, so do thousands of other people.

![image](https://user-images.githubusercontent.com/7098525/78605448-df047a80-789e-11ea-88e4-717743d47849.png)

Maybe, just maybe.. you're the one in the wrong.

Hey, maybe this will help?
![image](https://user-images.githubusercontent.com/7098525/78605529-107d4600-789f-11ea-9c20-2ecb0d93d2d6.png)

AoA fluids register before Blocks. I know this because I have printouts in the mod to tell me when it's happening (Enable verbose debugging in the aoa config and you'll see it yourself).

Maybe even more?

![image](https://user-images.githubusercontent.com/7098525/78605587-30ad0500-789f-11ea-801a-1df416b084ea.png)

Here's me USING the block. In 3.2.6

Now when you're done playing superiority complex, provide the full crash report & log file.

Thanks :)

**Comment by 0ct0ber** [comment]
I don't have a superiority complex, I just simply tried everything, looked through the code myself and all it said was a class init error. Looked at what others with the same issue came up with (no solution). Looked at the curseforge page several times, and didn't find any dependency info. And this was before I spent hours doing manual security checks. It turns out this was an old build of forge issue, but I had no way of knowing that (crashed before I got the dependency message) and everything pointed to it being a code error. The highly similar class names along with the text of the error made me confuse CandiedWater with CandiedWaterBlock. If you think they're the same, then yes it looks like a recursive constructor problem. Your responses weren't very polite and simply denying, saying I didn't provide enough info after trying everything wasn't very encouraging. I didn't want to call you what you called me, but I felt roughly the same about you before you said that. I think it's fair to say simply that all the hints to the underlying problem were pointing the wrong way.

I have been using a custom version of forge, but I just tried the normal one; turns out forge 14.23.1.2589 just crashes without a dependency message (same error).

**Comment by 0ct0ber** [comment]
@Tslat Waiting for a reply... what you said was extremely disrespectful, and the overall language you've used is not how you'd talk to a person in real life. It's how you'd talk to someone if you were their employer, think you're always correct, hate those that point it out and don't want anyone correcting any mistakes. Yes I was trying to point out an error at the time, but nothing in the way that I spoke indicated that I was trying to seem superior (which is a serious issue, and I think you have that problem). 

I talked calmly like a normal developer addressing a problem, while you used caps and a militaristic way of speaking.

If I ever took up a project like this, I would not demean someone simply for pointing out a problem, whether they are right or wrong. I would take it patiently and realize that they sincerely think there is an issue, and handle it like an adult.

**Comment by 0ct0ber** [comment]
Not everyone who reports a bug is just a feeble mod user, sometimes they are actual developers that look into the problem in order to try and lighten the load of the other dev. I did not try and help to disfavor you, I tried to help in order to help you.

**Comment by Tslat** [comment]
I asked you to provide a full log and crash report.

You ignored me, then created a PR - assuming you know better than me and pushing forward a "fix" that was actually creating the issue you thought you were fixing. Not to mention it wouldn't even compile had I used it.
Also not to mention that my github clearly states that I do not accept PRs.

I have a lot of things to do, and only limited time.
Without you providing the log file and/or crash report in full, I have nothing further I can do with you, and so the next valid step is to close the PR.

You then go on to insinuate that I'm _so obviously_ wrong that I haven't even played or tested my mod in the last 3 months, which is straight up insulting.

So to sum up:
1. You report bug with insufficient details.
2. I request sufficient details.
3. You ignore me entirely and go on to just shove a supposed fix in my face, despite my policy stating to not do so as it will be ignored.
4. You then directly insulted me and insinuated that I don't even know if the mod runs, and that you're so clearly right and I should just accept whatever you say.
5. You continue refusing my request for sufficient information
6. I close the report since I can do nothing further without sufficient information (Hence the term 'sufficient')

When you report a bug to a dev, and the dev says they need more info, don't turn around and throw it in their face, play as if you're superior to them because 'you know' how to fix it, and the dev is so incompetent they likely haven't even tested their mod in months, then go against their specific policies and continue to ignore requests for info.
When a dev says they need more info, it's probably because they need more info.

As for solving the problem, your crash report noted a ClassNotDefFoundError. This error does _not_ occur because a variable isn't initialized. It occurs because a class is missing entirely. If a class is missing entirely, this is a very different issue, since normally the mod would not even compile with a missing required class.
Since you snipped out the rest of the crash report, I was not able to see what class was missing, and so I couldn't diagnose any further.
Had you provided a full crash report and/or log, I could have seen what class the mod thinks is missing, and worked on it from there. 
When a user provides a log, I also check several other things, such as memory usage/allocation, other mods present, forge version, mod version, initialization status, and various other debug info.

If you have an issue with sensitive information such as your full name being in the log, open up the file in a text editor and find/replace your name with a generic, then provide the file.

As a future reference - generally speaking, the developer of a mod tends to have a somewhat better idea of the backend of a mod than a player does. Maybe not always, but I'd say a fair majority of the time at the least. With that being the case, maybe it's worth just humoring the dev when they ask for additional info and working with them rather than trying to go around them and do your own thing.

I do appreciate that you tried to rectify the issue yourself via a PR, it was a nice try and I'm happy to see you tinkering a little with code for fun.  However I really did just need that crash and/or log to solve the issue.

**Comment by 0ct0ber** [comment]
Replying to each section roughly from top to bottom...

I'm going to provide a log at the end since I'm around done discussing for now, and I'd like you to tell me if you agree that most of the log doesn't seem to hint towards the problem.

I did not try and ignore your comment, I was just already going to submit a pull request right after posting the issue (and didn't expect you to reply so soon). When I feel interested I usually look into the problem myself first, and post the issue and the commit at the same time. I'd like to help people fix a bug quicker when I have the time and energy, I just didn't like how you treated me in response.

>You then go on to insinuate that I'm so obviously wrong that I haven't even played or tested my mod in the last 3 months,

Look, I'll explain why I thought you hadn't tested it. There are two download routes for the mod- one on the CurseForge Files tab and one on the gamepedia. The CurseForge download route has no installation instructions and doesn't tell you that you need a specific forge build. I was running 1.12.2 Forge mostly unmodified except for some security loggings, and your mod immediately crashed before the game even finished loading. I had no other mods and figured that I followed all of the right instructions given the aformentioned difference in download routes. I now know that you indeed tested it on the latest build of forge, but it seems you didn't on this version, and I had found no information telling me that a specific build was needed.

When I actually tried looking into the error, as I normally do, I saw the error occurred right when a static variable was referenced, so I assumed it was a static initialization problem. If one thinks it's a variable being referenced that's not already initialized yet, then it's easy to mistake CandiedWater for CandiedWaterBlock and see a recursive loop. When I make a commit I actually try and make the change as small as necessary, and not change the rest of the code in the process as the author worked hard to make it that way.

>which is straight up insulting.

I only said this after I felt insulted by you. I actually looked into the problem and thought I found a source to it in the code. I followed the seeming installation instructions (drop mod in folder, no special details). You didn't take a second to think that maybe I had some wisdom behind which part of the log I selected, and started using this militaristic language and caps. It felt like a denial of the issue, and also a denial of my own knowledge. I think you can admit your language came across as a rather snarky attitude.

What I have to correct you on is one thing- fixing problems = acting superior. Perhaps you've only been around people that attempt to correct problems in order to act boss or smear. Perhaps you've not experienced the large GitHub repositories that openly welcome people who want to make small commits, while still taking pride as being the lead developers of a project.

Or maybe you think you're a math teacher and I'm a student. I've been making plugins and mods for five years now, and help others find issues with their code on an active basis... I don't just "tinker" but have my own projects at hand. I'm versed enough in Java to know it like English and have learned a bit of 4 other languages. But that aside, even a math teacher gets it wrong sometimes, and is corrected by a student. A good math teacher is atleast open to the possibility at the start.

There is no insult intended from me just because I try and help provide a solution. Sometimes we all get badly confused and there's a miscommunication, you know? (In that case, just say HEY, slow down, there's some confusion mate, rather than You're Wrong! You're not following my orders!).

If you still think I believe I am superior, I find it rather silly at this point. I don't think I am, whether it's you posting a comment/commit on my project (most are actually private) or it's me posting on yours. We're all smarter in different ways, it only really matters to me when someone is being a douche about who's smarter.

I don't mean to hurt by this, but I see the irony when a dev of an intellectual property thinks they are in charge of everyone who uses it, and calls anyone who corrects a mistake, successfully or not, "superiority complex". If you think you are the math teacher, you think you are superior, not the other way around.

**Comment by 0ct0ber** [comment]
Anyways, here's the log: https://pastebin.com/rHqidT40

**Comment by 0ct0ber** [comment]
Anyways, here's the log: https://pastebin.com/rHqidT40

**Comment by Tslat** [comment]
Thanks for providing your log.

A couple things worth noting:

1. You're only allocating 2GB of RAM - you'll probably want around 2.5-3GB minimum for a modpack with AoA. It's a big mod and takes up a bit more resources than an empty build.
2. You're (as you've correctly discovered now) using the wrong version of forge. One of the many reasons I request a full log up front is because even though forge is supposed to stop the init if it's on a version less than what AoA specifies, it fails to do so on some occasions. Finding this in the log is one of the first things I do, and it tends to solve a lot of problems.

As for the crash report - to help you in the future:
![image](https://user-images.githubusercontent.com/7098525/78644637-8910f080-78f9-11ea-9af6-e82b838620b9.png)

A ClassDefNotFoundError exception is thrown when the runtime cannot find a class that it is supposed to be referencing. This is extremely unusual because unless you're dealing with dependencies, your project will often just outright not compile unless it has that class.
When forge fails to find a class in a mod, it's usually a sign that the forge version is outdated, or a mod version is outdated.
At no point does it indicate a null reference. This would be indicated by a NullPointerException error.

As for the superiority complex thing - I'll take it back.
You're correct in assuming that the vast majority of people who come here and do what you just did do in-fact think that they know better than anyone else. It's easy to become bitter after so many such experiences.
I apologise for throwing that out at you.

However, I will still request that if/when you report bugs to a mod, you provide the full crash and/or log. It may not seem like it, but there's a lot more info available in those files than you may think. This is very important for a dev, and it's extremely frustrating having a section of a crash provided, rather than the full thing.

Sorry it came across so bitter, hopefully you can continue to enjoy AoA

On an unrelated note - I'd recommend you add Phosphor mod as well, as it really helps with lighting engine issues that MC has (especially in floating dimensions like Haven/Celeve/Lelyetia)
