### ISSUE TITLE
Tyrosaur Earthquake Change.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#139]
The Tyrosaur fight is often sighted as unfun due to his massive hp which is fine, but his earthquake attack is unseeable, instead you get a vague text to indicate when the attack is in progress. (Still have no idea how the attack works). All of these flaws turn Tyrosaur into one of the most unfun bosses in the game.

To make the fight more enjoyable, 
- Give him the Polar Bear attack animation and set it as its earthquake attack. This would be a better indication than some random text.
- Give the earthquake a louder rumbling sound to give the earthquake a more threating appearance (And so I can hear it over the music).
- Make it so that the Earthquake creates dirt particles that appear on blocks for a quick second to show the exact radius of the earthquake. (tnx Cruuk)

**Comment by Immortallis1** [comment]
I'm not too sure about the polar bears as I haven't played 1.10 much lol

Definitely agree with the second one. When the presence of music makes the boss significantly harder, there's an issue.

**Comment by Sagisolar** [comment]
https://youtu.be/OXGAFZqh2dc?t=107

**Comment by Immortallis1** [comment]
yeah right now the earthquake is kind of underwhelming

**Comment by papabean** [comment]
I wholeheartedly support this; Tyrosaur feels kinda unfinished isn't really fun to fight for the reasons to provided, but the changes you suggested would otherwise make him much more fun to fight and less RNG-based (or at least trying to jump after a static period of time passes, as that is how his earthquake move works, if I remember).
