### ISSUE TITLE
Quick ideas for tinkers stuff

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#1401]
-Charged (lyon): Something that makes shockwaves when attacking because it sounds cool (maybe like betweenlands style shockwaves idk whatever feels cool, possibly like the iromine staff i forgot what it’s called)

-Drain soul power to break blocks faster or do more damage. 

-Same but with energy or battle rage

-Ghoulish: Increased effectiveness in spooky (erebon maybe) environments

-Expertise (or adept or skillful or proficiency or whatever synonyms): Increased hunter xp/foraging xp/chances when used to kill or mine

-Cryogenesis: Repairs itself in icy environments to copy ice armor and give it a cool name

-Death Perception: X% (tiered but really small) chance on hit to deal a really high amount of damage and play a cool sound like Xxeus’ death sound which fits perfectly. Spill their guts with one swift strike. Fails on bosses

------
Part 2:

-Avarice - Mobs killed have the tendency to drop extra coins. This is independent of looting or whatever, and even mobs from other mods may end up dropping coins if this is used.

-Haunting (maybe better name) - attacking with this thing summons spirits or wisps around the target that deal damage and inflict various negative potion effects

-Haunted - whatever haunted gb does

-Dragon Rage - ranged projectiles create the ender dragon/flaming fury cloud

-Inferno - sets target on fire, and does more and more damage when hitting targets on fire. Damage resets if target isn't on fire. Not sure if fire immune (i.e. can be set on fire but don't take damage from it) mobs should be affected, probably not to differentiate it from the other increment-damage modifier (think it was on manullyn)

-Blazium should also get autosmelt (is a tinkers trait already) just because

**Comment by Immortallis1** [comment]
PART 2:

-Avarice - Mobs killed have the tendency to drop extra coins. This is independent of looting or whatever, and even mobs from other mobs may end up dropping coins if this is used.

-Haunting - attacking with this thing summons spirits or wisps around the target that deal damage and inflict various negative potion effects

-Dragon Rage - ranged projectiles create the ender dragon/flaming fury cloud

-Inferno - sets target on fire, and does procedurally more damage when hitting targets on fire. Damage resets if target isn't on fire

-Blazium should also get autosmelt (is a tinkers trait already) just because

-Modifier that gives levitation to enemies

**Comment by Immortallis1** [comment]
PART 2:

-Avarice - Mobs killed have the tendency to drop extra coins. This is independent of looting or whatever, and even mobs from other mobs may end up dropping coins if this is used.

-Haunting - attacking with this thing summons spirits or wisps around the target that deal damage and inflict various negative potion effects

-Dragon Rage - ranged projectiles create the ender dragon/flaming fury cloud

-Inferno - sets target on fire, and does procedurally more damage when hitting targets on fire. Damage resets if target isn't on fire

-Blazium should also get autosmelt (is a tinkers trait already) just because

**Comment by Tslat** [comment]
Done in 3.3
