### ISSUE TITLE
Re-evalulate enemy weapon immunities

### ISSUE THREAD

**Issue by Lithobraker** [Tslat/Advent-Of-Ascension#1587]
Referring to the enemy attributes that make them immune to certain weapons, I believe- and have believed for a while, that this feature is unintuitive and adds nothing to the mod in terms of strategy or challenge.

In video games similar to this, weapon choice is often dependent on the circumstances at hand. Certain weapons, by virtue of their abilities and stats, are better suited to certain situations. 

For example, facing an Arkback- a large, powerful melee mob with the ability to damage nearby players outside melee range- would be best dealt with using ranged weapons of some sort.
But the thing is totally immune to guns and bows, leaving only melee- a poor option to be sure- and staves, which are a pain to sustain and require a lot more investment than other weapons, compared to their performance. This forces players to make a choice- either bite the bullet and try to melee it, or potentially force players to use a playstyle they don't like by gathering runes for staves.

By contrast, consider the vanilla Creeper. Engaging it in melee is a bad idea unless you're sufficiently skilled- it's much better to kill it at range, if you can help it.
But if the creeper was immune to bows, it would force players into a disadvantageous position- robbing them of the ability to use basic strategies because of a magic icon above its head.

This isn't interesting or challenging- it's a heavy-handed approach to forcing weapon diversity in a player's arsenal. But... having enemies with resistances and immunities isn't an inherently bad thing.

The core of the issue, I think, is that it's attached to weapon types, and not, say, elemental damage, as an example.
Lots of games use elemental damage to encourage players to carry different types of weapons for different situations, without restricting their playstyle. If you want to play as an archer in any other game, your resistance and immunity-related problems will not come from enemies just ignoring arrows for no reason- rather, it comes from having to use a bow which doesn't deal, say, ice damage, to take down an ice elemental.

This system can coexist with the standard tactical weapon choice problems players face, as it's not related to the weapon type itself- but instead a property of any weapon.

If you were to fight the Nethengeic Wither with a Wither Bow, as an example, you might find that it's immune to the arrows because it's immune to Wither damage- rather than being immune to a weapon type(I know the Nethengeic Wither isn't immune to weapon types, it's just an example)

Perhaps Cotton Candor could be immune to the Color Cannon not because it's not a staff, but because it would deal Light damage? Maybe he'd even be a little weak to Wither damage.

Aside from this, the only alternative I could suggest would be to simply remove weapon immunities without a replacement system. It feels like a clunky, outdated mechanic more than anything else.

I did some searching on the discord and github and couldn't find any other discussions like this.

**Comment by EnderdragonLord** [comment]
To add my opinion onto this, I think adding config options to control which mobs should have specific immunities, like how you already can for hunter mobs would help out a lot with that.

Adding support for different weapons from other mods could also help even things out, by default from what I've seen while playing, every attribute except magic, guns, and blasters are able to automatically support weapons from other mods, a Pickarang from Quark for example would already count as a ranged attribute because it's thrown as a projectile, now think about using spells from Electroblob's Wizardry or using the Thaumcraft Gauntlet as your staves or the Revolver from Immersive Engineering as your gun, it would add more variety for those who hate playing with those specific class of weapons, it would also be supported by anything that boosts guns, blasters, or magic damage, I can see an issue with this though, I don't know how possible it would be to add this as a feature, even if it's just a config, especially when there's a lot of mods to support that adds magic or guns.

Other than those, I personally think the system is fine and adds something new and interesting for mobs in general, elemental damage would be a cool idea in design but I feel like that it might overcomplicate the mod and I don't know how weapons from other mods would support it, I do agree though that immunities can get extremely annoying for certain mobs, especially the Soul Scurry event where all the mobs are immune to three different classes of weapons including melee and ranged, even though it's really rare to get it as an event, I feel like it should've been like hunter mobs, where it gets harder as you progress through each tier of dimension, this way those who play the mod are more prepared, and are more aware about the whole system by the time they reach further in.

**Comment by Cruuk** [comment]
I should let you know that Arkback isn't immune to Blasters

**Comment by AstralScourge** [comment]
There's not much denying that they were designed to basically force people to use other weapons, but for me at least they're rare enough to not cause too many problems (especially with sphinx no longer being melee immune).

As for Cotton Candor that's probably the worst/most hamfisted one ("see? runation is required to kill the boss it's an important skill") but that's probably a topic for a boss update.

**Comment by Lithobraker** [comment]
> 
> 
> I should let you know that Arkback isn't immune to Blasters

Oh. That completely slipped my mind.
This whole system still feels silly and uninteresting to me, though.

**Comment by profilename14** [comment]
I agree that some enemies simply being completely immune to damage from certain weapons feels like an unintuitive system, but I feel like simply removing it if we cannot add elemental damage (which I would definitely be interested in, but I am not sure if it would conflict with other mods) would leave in place little reason to change the player's weapons. There are tactical advantages to changing weapons, but that doesn't give any reason for someone to look into blasters/staves when they are using guns. Additionally, melee weapons like greatblades have few tactical advantages over ranged weapons.

Instead of removing this weapon immunity system if we cannot replace it, how about modifying it into a resistance system? For example, something like the tortione could have an 80% resistance to guns, ranged weapons, and melee weapons. This would make it no longer unkillable unless you have explosive weapons or blasters, but reward players who bring those weapons with a much easier time fighting the mob. Some mobs would still have 100% resistance, like destructors, but most would have percentage reductions in damage instead.

**Comment by Lithobraker** [comment]
> 
> 
> I agree that some enemies simply being completely immune to damage from certain weapons feels like an unintuitive system, but I feel like simply removing it if we cannot add elemental damage (which I would definitely be interested in, but I am not sure if it would conflict with other mods) would leave in place little reason to change the player's weapons. There are tactical advantages to changing weapons, but that doesn't give any reason for someone to look into blasters/staves when they are using guns. Additionally, melee weapons like greatblades have few tactical advantages over ranged weapons.
> 
> Instead of removing this weapon immunity system if we cannot replace it, how about modifying it into a resistance system? For example, something like the tortione could have an 80% resistance to guns, ranged weapons, and melee weapons. This would make it no longer unkillable unless you have explosive weapons or blasters, but reward players who bring those weapons with a much easier time fighting the mob. Some mobs would still have 100% resistance, like destructors, but most would have percentage reductions in damage instead. It could even be made to include a weakness system for some mobs, like a powerful ranged mob that takes 50% extra damage from explosions.

I think the argument that without this system there's little reason to change weapons is kind of a broken one- because most enemies already don't have any immunities to begin with.
They're not prevalent enough to be a major mechanic, but just enough to be annoying.
Of course you won't want to use a greatblade or a sword against a distant enemy- but that doesn't make them bad, because they work very well in short range.
Trying to aim a gun or draw a bow versus an enemy in melee range is pointless when a sword is stronger and easier to use. This is just fine! That's the kind of tactical decision I meant.

If a system like this is the only reason a person feels like they should use staves or blasters, then that indicates a problem with staves and blasters- it does not seem like good game design.
It's artificially implementing a reason to use weapons which otherwise offer no tactical advantages. It's like putting a bandage on a lost limb. It patches over the problem, sure, but the issue is still there.

That said though, I think blasters are just fine, and I quite like them. Staves, though... as they are now, I would rather just try to power through without them if possible than bother investing into runes. I find that's still easier than using staves.

**Comment by Lithobraker** [comment]
I still feel motivated to carry a wide range of weapons even though most enemies don't have immunities, because they're different enough that they excel or fail in certain situations, naturally.

The only reason I'd ever use staves as they are is because certain enemies just require them to defeat. Even as powerful as they are, I'd rather just fight through normally than invest in staves- because that's easier.

**Comment by EnderdragonLord** [comment]
While thinking more deeply about this, I feel like one of the best solutions would be to remove most of the immunities entirely, keeping the ones like explosion, status, and special, while replacing them with new mob abilities. In vanilla for example, Endermen teleport when shot with any type of projectile, Shulkers occasionally go back into their shell in which they gain more armor points during that phase until they open their shell again and fire back, etc.

So taking some of the current mobs that have any sort of immunity and then replacing them with new abilities it would be like:

- Refluct : 
In older versions, they would reflect any type of projectile, the only way to kill them would be to use melee, in newer versions they were given attributes, in which imo I'm not a fan of because it made it too obvious that they're immune to projectiles and that was their special ability. To fix this, the attributes would be removed, they would still reflect any type of projectile, but this time it will damage you back and a sound plays as an indicator.

- Baumba: 
Firing any type of projectile at them will cause them to jump high up into the air without taking damage, similar to Endermen teleporting if you try to hit them with a projectile.

- Mechamaton: 
Sometimes they will gain a shield, which makes them immune to melee and projectiles, you're given the choice to wait it out or try and destroy the shield yourself.

- Tortione: 
Occasionally goes into its shell and gains extra armor points until it comes out of it. (think about the Shulkers) 

- Soul Scurry Mobs: 
Every few seconds, they'll turn more transparent and a sound plays as an indicator, this makes them immune to any sort of damage until they're out of that phase.

Those were some examples, some people might complain about not knowing that the mobs were able to do special abilities but imo that's what makes it fun, getting surprised by something new and then learning about it and planning out strategies for it. Endermen didn't need an icon to show that it would teleport away from projectiles, it was mostly discovered by players (or those who just searched it up on the wiki) I also didn't need to know whether or not a mob was immune to fire, which is why I despise those fire immunity icons, than again the icons could be turned off using a hotkey. Would be a pretty interesting idea for an update theme eh.

**Comment by Lithobraker** [comment]
> 
> 
> While thinking more deeply about this, I feel like one of the best solutions would be to remove most of the immunities entirely, keeping the ones like explosion, status, and special, while replacing them with new mob abilities. In vanilla for example, Endermen teleport when shot with any type of projectile, Shulkers occasionally go back into their shell in which they gain more armor points during that phase until they open their shell again and fire back, etc.
> 
> So taking some of the current mobs that have any sort of immunity and then replacing them with new abilities it would be like:
> 
>     * Refluct :
>       In older versions, they would reflect any type of projectile, the only way to kill them would be to use melee, in newer versions they were given attributes, in which imo I'm not a fan of because it made it too obvious that they're immune to projectiles and that was their special ability. To fix this, the attributes would be removed, they would still reflect any type of projectile, but this time it will damage you back and a sound plays as an indicator.
> 
>     * Baumba:
>       Firing any type of projectile at them will cause them to jump high up into the air without taking damage, similar to Endermen teleporting if you try to hit them with a projectile.
> 
>     * Mechamaton:
>       Sometimes they will gain a shield, which makes them immune to melee and projectiles, you're given the choice to wait it out or try and destroy the shield yourself.
> 
>     * Tortione:
>       Occasionally goes into its shell and gains extra armor points until it comes out of it. (think about the Shulkers)
> 
>     * Soul Scurry Mobs:
>       Every few seconds, they'll turn more transparent and a sound plays as an indicator, this makes them immune to any sort of damage until they're out of that phase.
> 
> 
> Those were some examples, some people might complain about not knowing that the mobs were able to do special abilities but imo that's what makes it fun, getting surprised by something new and then learning about it and planning out strategies for it. Endermen didn't need an icon to show that it would teleport away from projectiles, it was mostly discovered by players (or those who just searched it up on the wiki) I also didn't need to know whether or not a mob was immune to fire, which is why I despise those fire immunity icons, than again the icons could be turned off using a hotkey. Would be a pretty interesting idea for an update theme eh.

I completely agree with this! You're right about elemental damage in that it would further distance AoA's mechanics from other mods- but something like this would be much better.
I kinda forgot endermen were actually immune to bows in vanilla, but because they teleport away, it gives you a reason for it and is easy to learn.

The fact that a lot of these enemies don't give you any feedback when trying to use a weapon they're immune to- other than not taking damage- makes it quite clunky and unintuitive. They have the icons, but there's no way you'll be able to read those from a distance.
I think it'd be best if most of these were replaced with special AI and abilities for these enemies- that way, you'd make them more interesting and challenging without just giving them a nonsensical immunity.

Like, with how Enderman can teleport, it makes sense they might be able to dodge arrows easily.
But why exactly are Sphinxes immune to guns? Nothing about their design or behavior suggests it.
Maybe if they could, for example, summon a shield of spinning ankhs around them you'd be able to tell they're protected.

**Comment by Lithobraker** [comment]
I think a temporary solution that would make everyone happy would be to just add a config option to disable this immunity system.
Obviously, reworking this whole thing isn't gonna happen in the next version, nor the next after that.
This would probably go along with a huge mob/boss overhaul update. Until then, a simple config option would solve everyone's problems for now.
