### ISSUE TITLE
Dustopia mob reworks

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#161]
Dustopia being too easy is a problem that has been mentioned several times before. Dustopia was also supposed to be a creepy dimension, but it doesn't do much to give that feeling. I have a solution to both those problems: reworking the mob AIs in Dustopia.The AI replacements would be:

Arkzyne: The gravity effect is kind of annoying, especially considering you have to climb a tower to get to them. My replacement ability would be giving them high knockback. It would also have a "bleed" effect, which means it makes you loose half a heart every tick for 6 ticks.

Basilisk: When on low health, would run towards a nearby mob, biting it. When it bits another mob, it weakens and slows the attacked mob. Once the mob is impaired, the Basilisk will leach onto the weakened mob and steal its health. If it needs more health later, it will return to the already weakened mob, until it's killed off.

Crusilisk: Heals whenever a creature nearby (whether it's another mob or a player) is damaged. The only way to kill them would be targeting one at a time.

Devourer: Has high health and damage (comparable to Dracyon's melee attack). Would be transparent and "stalk" the player at zombie speed. When it's within 10 blocks of a player, it becomes opaque and starts running at charger speed.

Dusteiva: Has about 300 hp. It wouldn't move or deal damage, but would attract all players and mobs towards it, trapping the player in a pack of mobs.

Duston: Moves like a fast ghast, but does not fire projectiles. It can't fly over the trees, and would have a launch effect similar to the King Charger's, launching the player into the sky.

Dust Strider: idk

Lost Soul: Wouldn't move at all. It would naturally lose health, similar to the Rune Templars. It slowly rotates the player's vision towards it. If the player looks directly at it, it will heal to full health, damage the player, and teleport somewhere else.

Lurker: Has an large aura of darkness, which decreases the light level of blocks near it. The darkness going too deep into this darkness would give blindness.

Merkyre: Occasionally swaps positions with any player in its line of sight.

Stalker: The velocity would be swapped (it would be very slow when not being looked at, but very fast when a player has the static effect).

Stalker Prime: Same as a Stalker, but becomes invisible when a player has the static effect in addition to being fast.

**Comment by Cruuk** [comment]
Arkzyne: Ehh I kind of like the high gravity thing it has, maybe instead it needs to hit you first to inflict temporary high gravity rather than being an AoE effect?

Basilisk: It feels like there's too many "steps" in this ability to make it smooth for gameplay. Personally I think it would be better if:
Basilisk gives slowness on hit, but if it hits you more than once the slowness stacks, goes up to 5, lasts for 5(?) seconds. Can also lifesteal a certain amount of HP.
This would essentially make it a slight upgrade to the Bloodsucker.
Also maybe give it some armor just for the sake of at least 1-2 mobs in Dustopia having armor.

Crusilisk: Does this ability consider other Crusilisks? Cause you do know multiples of them spawn in a structure right? This is gonna make killing multiples of them really hard especially since they're so packed together in that small structure. I think I sort of prefer the current ability, they're already tanky as hell anyway.

Devourer: Now I like this one. The idea of a transparent mob with high vision following you around then charging at you sounds pretty cool. Imagine if Devourers could spawn in Dustopian marshes once biomes are re-added.
What if they occasionally played a creepy ambient noise while following a player?

Dusteiva: Hmm, I am a bit mixed on this one. It is interesting but at the same time it does sound a bit annoying. Maybe lower the hp to 180-200 and give it some armor so that cannons can be effective?

Duston/Dust Strider: Honestly I think the mechanic of these mobs is fine as it is. No need to change it, other than maybe changing the flying of the Duston so it's not that janky flying AI, giving it a version of the Ghast AI that doesn't go over trees as you mentioned.

Lost Soul: Not sure about this one, it sounds like a worse version of the Occulent, and I know people just love that thing so much.
Maybe the player's vision gets locked on it only if they look at it? The screen-lock would last for 2 seconds and has a 20-second cooldown per Lost Soul. It would still have it's unique heal ability.

Lurker: Neat concept, but maybe it would be better if it just disabled any light near it (wouldn't affect Dustopian lamps), and still had it's wither-on-hit.

Merkyre: Interesting concept, but again it's a structure mob so that type of ability may get annoying.

Stalker/Stalker Prime: Sounds good enough, makes it more akin to Slenderman.
Also, please make the screen effect animated.

Supporting this because Dustopia needs all the help it can get in terms of difficulty.

**Comment by Sagisolar** [comment]
Yeah along with this suggestion with the strengh nerf. Dustopia can get the victory royale in difficulty.

**Comment by Immortallis1** [comment]
> 
> 
> Dustopia can get the victory royale

No.

IIRC disabling light near it is a hard thing to deal with? 
I think the hunter mobs (crusilisk/arkzyne) are mostly fine as is, nobody is complaining about them. But the others look cool for the most part.

**Comment by Sagisolar** [comment]
Yes.
If your gonna buff a dimension, might as well buff everything so people will stop complaining about its difficulty.

**Comment by Immortallis1** [comment]
that's not exactly how it works, you only buff what needs to be buffed

**Comment by Sagisolar** [comment]
But some people will keep complaining

**Comment by Sagisolar** [comment]
Still buff them

**Comment by Cruuk** [comment]
> 
> Yes, it includes other Crusilisks. The idea was forcing the player to target one of them at a time. You do have a point about its tankiness, maybe nerf their stats a little? I just feel the concept of randomly being flung in a direction is cheap.

I like the high stats though, it's really fitting that the final hunter mob has such crazy high stats.

**Comment by DiamondWalker** [comment]
> 
> 
> > Yes, it includes other Crusilisks. The idea was forcing the player to target one of them at a time. You do have a point about its tankiness, maybe nerf their stats a little? I just feel the concept of randomly being flung in a direction is cheap.
> 
> I like the high stats though, it's really fitting that the final hunter mob has such crazy high stats.

I had actually forgotten that. In that case, I think it should have both the special ability and high stats. There are already high level hunter mobs with tanky stats (see fungock). By the time you fight Crusalisks, you have already beaten most bosses and are likely quite powerful. It being incredibly powerful and difficult would make sense, since it's probably the last hunter mob you'll face.
