### ISSUE TITLE
Rune Rework

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#1671]
I'm sure I don't have to explain why runes are bad. They clutter your inventory and make you take countless boring trips to the same structure over and over.

**_Recipes_**
The first change I'd make is readd a rune shrine recipe. This is because the new system would allow you home. This would also mean the wind altar's shrine would be removed for consistency. The recipe for runes would also be changed. Rather than one chunk for 16 runes, you'd need 9 chunks for 1 rune. This is because now you'd only need one of each rune.

**_Rune Mechanics_**
Runes wouldn't be stackable and act like ammo anymore. Instead staves would consume runic energy. Runic energy would have several variants (each rune has its own runic energy type). Runes would store this runic energy. All runes would have unpowered and charged variants, which are made with either unpowered or charged runes (duh). Unpowered runes would have much higher energy capacity (like 10,000 units), but would need to manually be recharged. Powered runes would have less units (like 100) but would slowly fill themselves up with energy. As a rune's energy runs out, the colored part would become darker.

**_Rune Creation/Charging_**
Runes can now be charged either with rune posts of the appropriate type or with charged runium (the later being the reason rune shrines would be craftable, since now they could be used by themselves). The only difference is charged runium can only power runes that have been engraved for a specific energy type. Runes are engraved automatically the first time they are charged with rune posts (this does not mean you can use another rune post to change or charge an engraved rune)

**_TL;DR_**
Rune shrine has recipe. Runes are more expensive. Runes can be charged with charged runium or the correct rune posts but only when they're engraved, which happens when charging blank runes at a post for the first time. Unpowered runes would have more uses, but powered runes charge alone.

**_Extra stuff_**
Staves should probably require more energy than the amount of runes they currently require. I'd say a good conversion rate would be 5 energy unites per rune. It'd also be nice to see rune pouch reintroduced as an optional runandor item with less slots.

**Comment by profilename14** [comment]
This sounds like a far better-designed system than what we currently have. With runes acting as rechargeable batteries, it takes the interesting part of the current system and effectively removes all of its problems. The one part of the current system that is interesting is the fact that staves can have "synergies" with each other, or that a player can use a set of staves that have similar rune costs to cut down on the number of rune types they have to carry. Of course, with each rune costing about 4 runes minimum by default (and some costing up to 12), it is nearly impossible to use staves without filling your inventory with them and having to get more every 15 minutes. Compared to guns, which all only require a single, incredibly easy to craft, bullet, there is no reason to use most staves in normal gameplay.

An example of this can be seen with the Noxious staff. Without Archmage (which staves should not be balanced around due to it being a very high-level infusion enchantment), a noxious staff consumes 6 runes per shot. If someone were to want to use a noxious staff 192 times, they would have to carry around 18 stacks of runes, which fill two rows of their inventory. However, they could instead simply use a gun, which they can fire 192 times while carrying only 3 stacks of ammunition (which remember, are **far** easier to get than runes).

This suggestion gives us two types of runes, a basic rune that can be recharged at a rune shrine and has higher maximum energy, and a rechargeable rune that regenerates over time. Each of these are charged and assigned a specific rune type at a rune shrine, making acquiring different kinds of runes for a staff still require adventuring through dimensions. However, players can create their own rune shrine wherever they want, so when a player wants to recharge a rune for a staff that they often use, they can simply recharge it whenever they go back to their base. 

With this system, a player would be able to use a wide array of different staves, and the maximum amount of runes that they would have to carry around would be 14 runes (one for each type) in the worst case. For runes required by uncommonly used staves, the player could take a charged rune, but for runes required by often used staves, the player could take a normal rune. A player could even use multiple rechargeable runes if they are only using a single staff very often. These rune types give players more options for how they want to customize their ammunition and more strategy for which staves they want to use together. Additionally, with rune shrines buildable inside bases, players who use many staves can easily recharge their ammunition without having to worry about being forced to walk a long distance through a dangerous dimension. 

My only complaint is that I feel like the normal rune could have a slightly smaller limit, maybe 2500, in order to not overshadow the charged rune as much. Still, even with 10,000 durability, the rechargeable rune has its uses. Also, Runation would be better off not gating runes with this system (which is fine, as it wasn't a fun skill anyway)

With 2500 power, a normal rune effectively gives 500 runes for a staff. Going back to my previous example of the Noxious staff, the player could carry around 3 runes to get 250 uses out of the staff. Additionally, the ammunition required for the staff does not require mining for runium and walking to a rune shrine to refill. This puts it about on approximately on par with guns, which fire 192 shots with 3 slots of inventory and are about as powerful as damaging staves. Staves have slightly higher ammunition per slot in some cases and can use archmage to lower the amount of energy used, but guns generally share the ammo they use more than staves (they usually use limonite pellets) and don't require sets of runes (a Noxious staff requires 3 runes minimum while guns could be used with only 1 stack of bullets).

Overall, this is an incredible suggestion, and I feel like it will make staves one of the most interesting and fun to use weapon types in the entire mod.

**Comment by EnderdragonLord** [comment]
I'm up for having shrines at your house for faster Runation, but I'm against completely removing the shrine structures. Instead I think they all should stay, but using them would grant 5x the amount of experience or something like that to encourage exploring for them. They do need a whole redesign though, right now they're mainly just weird floating platforms so it would actually be pretty cool for them to look more like ruined structures or altars, if you played RuneScape in which I'm pretty sure that's what inspired Runation, it had some really cool areas based on the element of each Runecrafting altar. (Personal favs of mine include Fire, Cosmic, and Blood)

The old rune system should be introduced as a new item called Rune essence but it would take a bit more of Runium/Charged Runium to make, for example you can make Fire Rune Essence which can be used for making new staves through infusion crafting, making rune banner patterns, or charging runes by a minimal amount. Maybe Alchemy too, but not sure how it's going to end up in the mod yet lol.

Also I think you should be given the option to get any type of energy from any type of shrine, like being able to get Life from Wind, this is to make getting the energy as easy as getting bullets, but doing this would reduce the Runation experience by half and you get slightly reduced energy compared to using the corresponding shrine. So yeah, I think Runation and staff weapons deserve a lot more over the massive potential they have and this is a really good suggestion to improve it.

**Comment by profilename14** [comment]
I don't feel like natural rune shrine structures would have to be removed for this system to be added. The way that I see it would work is that the player would have to explore for a natural rune shrine and either use their runes on it, or mine the shrine's rune posts to make their own shrine at home. This system would not only let natural shrines stay useful, but make further shrines beyond the first one you find useful if you want to make multiple bases. I do agree that more should be done with the shrines though, as they would could look very nice as floating islands with some scenery in them.

Additionally, basic/powered runes of a certain type could still be used for banner crafting. Currently banners can take somewhat rare materials like creeper heads as ingredients, so runes of specific elements would fit. In regards to crafting recipes, the current staves could either remain using a single rune of their element (which would make them a bit more costly but still somewhat easy to craft, mainly only requiring 9 runium) or have a different material like a fire charge. Runic essence could be a neat idea if it interacted with other skills like Alchemy, although runes will already be able to be recharged on the go with charged runium.

Having any shrine recharge your runes could be a neat idea, as it would not make the player have to build 14 rune shrines in their base. Maybe there could be a special later game rune recharging station that recharges any rune, still making it worthwhile for the player to build multiple of their own shrines during earlygame but letting people with smaller bases avoid having to build too much.

**Comment by DiamondWalker** [comment]
> 
> 
> I'm up for having shrines at your house for faster Runation, but I'm completely against removing the shrine structures. Instead I think they all should stay, but using them would grant 5x the amount of experience or something like that to encourage exploring for them. They do need a whole redesign though, right now they're mainly just weird floating platforms so it would actually be pretty cool for them to look more like ruined structures or altars, if you played RuneScape in which I'm pretty sure that's what inspired Runation, it had some really cool areas based on the element of each Runecrafting altar. (Personal favs of mine include Fire, Cosmic, and Blood)
> 
> The old rune system should be introduced as a new item called Rune essence but it would take a bit more of Runium/Charged Runium to make, for example you can make Fire Rune Essence which can be used for making new staves through infusion crafting, making rune banner patterns, or charging runes by a minimal amount. Maybe Alchemy too, but not sure how it's going to end up in the mod yet lol.
> 
> Also I think you should be given the option to get any type of energy from any type of shrine, like being able to get Life from Wind, this is to make getting the energy as easy as getting bullets, but doing this would reduce the Runation experience by half and you get slightly reduced energy compared to using the corresponding shrine. So yeah, I think Runation and staff weapons deserve a lot more over the massive potential they have and this is a really good suggestion to improve it.

I think the system I suggested has been misunderstood. The idea is you'd take a blank/empowered rune (whichever you prefer) to a rune shrine (they wouldn't be removed) and you engrave and charge it with that energy type. Once the energy is drained it'd still be engraved, so you could either go back to the same rune shrine or use your home rune shrine to recharge it with charged runium. This would make it so that once you get to deeplands rune shrines will only be used for engraving blank runes.

**Comment by EnderdragonLord** [comment]
Ah, okay yeah I did misunderstood it in some parts, thanks for clarifying it a bit more, I did see the part about removing Wind shrines and thought it said that the structures should be removed, I'd still love to see them get reworked though in design and mechanics.

Also yeah banners do use rare items like Creeper Heads true, but I'm also wondering how it'll accept the new types of runes if the idea becomes implemented, like would it have to be drained out or charged for it to work in the banner recipe? (That's if another item isn't used instead to take the old runes place in the recipes)

**Comment by profilename14** [comment]
At least if it's possible to program, I'm assuming that runes would be able to be inscribed into banners no matter what their charge is. The main thing the player is doing in this scenario is inscribing the rune's symbol into a banner, so it wouldn't matter if the rune is empty or full on energy, just that it is inscribed with an element.
