### ISSUE TITLE
AoA NPCs are Villagers instead of weird humanoids.

### ISSUE THREAD

**Issue by TheWitherlord** [Tslat/Advent-Of-Ascension#1752]
In order to fit the theme of the 1.15.2 update a little more, I think it would be nice to see all the NPCs in the mod have a villager like appearance.

https://minecraft.gamepedia.com/Villager

 They can also have workstations made from AoA materials to give them access to specific professions.

The Banners could be sold by the Shepard villagers or crafted on the loom with special materials.  (The Herald could still be a thing)

Naturalists could have a special flower pot that allows them to sell certain things.

Metalloids can be attracted to anvils or iron blocks?

Lottomen could stay similar to that of wandering traders.

Realmshifters only appear once you open your first portal.

Many dimensional npcs can still have their iconic looks.

**Comment by Firch** [comment]
Yes! I really hate how npcs in AoA are humanoids now.  Humans in minecraft are meant to be intelligent race that can do something and not only trade (aka playable characters).

**Comment by SKnight1207** [comment]
And it will open up a whole new possibility of not just being able to trade with them like villagers, this will allow 1.15.2 industrial foregoing compat cause aoa npcs dont count as villagers

**Comment by SKnight1207** [comment]
so the villager trader cant be used

**Comment by EatingSilencer** [comment]
I'm going to say I don't approve of this one. 

I don't see how making AoA NPCs look like villagers when porting to 1.15.2 makes them "fit in more". Vanilla villagers exist in 1.12.2, by this argument they should already have been changed to look like vanilla villagers.

As for jobsite blocks, I would approve of AoA NPCs functioning like vanilla villagers for consistency sake. 

Just a reminder that Metalloid is not an Overworld NPC anymore, so not sure how that would change things here.

> Humans in minecraft are meant to be intelligent race that can do something and not only trade (aka playable characters).

Since when has this been a thing? Who was determined that their meant to be this way? I feel if this was a serious problem, people would have complained by now. I don't see anything wrong with an intelligent creature wanting to trade and do nothing more.

-----
The only way I can see this suggestion being viable is if the NPCs have copyrighted textures meaning they need changed anyway. 
There's also the issue of originality - but I won't get into that.

**Comment by EnderdragonLord** [comment]
Imo, I don't think most NPCs should be a Villager, I'd rather much would prefer variety between different races of NPCs that really showcases what type of inhabitants are living within the areas and dimensions you explore. For example Mysterium had Gorbs, Lunalus had Zals, Dustopia had Primordials, and Vox Ponds had one NPC that looked like it went through a mutation, it gave me the feeling that there's much more to see than just different variations of villagers and that they're not the sole friendly race in the game. 

When I played through Galacticraft, I actually found it really boring that they just made their own mobs into variations of existing vanilla mobs rather than trying something unique and different so you'd see stuff like Endermen with Oxygen helmets on or blue Villagers, I had wished that they made different types of aliens instead.

I think it would be better off for only a few Overworld NPCs to become Villagers while others stay humanoid like the player or be turned into another type of race, I can see Realm Shifters being a type of demon or some type of Ender creature originating from The Nether or The End, and there's also the Troll Traders already which I liked their inclusion a lot.

To add more suggestions into this though and improving the NPCs in the future, Lottomen should have new models since they all do look the same with different skins. Have it where the Overworld one is a Villager, Nether one is a Pigman or a Piglin (If it ever ports to 1.16), Lunalus is a Zal, Dustopia is a Primordial, etc.

Skill Masters should be merged into one universal NPC imo, they each only have one trade split across different dimensions and also because I sometimes have trouble finding a specific one. I also think some of the randomly spawning NPCs should spawn inside structures instead, Assassins spawning around small camps similar to the Pillager Outposts, Naturalists spawning inside giant trees, and Realm Shifters spawning occasionally around Ruined Teleporters (or near broken Nether Portals in 1.16, but I really like the idea of having them only spawn after opening your first portal.) 

All in all I mainly just wanted to share my thoughts on this, giving them the 1.14 villager mechanics would be great though and would have a ton of potential for some cool stuff.

**Comment by Firch** [comment]
> Since when has this been a thing? Who was determined that their meant to be this way?
Even in minecraft dungeons you can't pick villager as a character; all playable characters in minecraft series (not sure about story mode) are humanoids

**Comment by EatingSilencer** [comment]
> Even in minecraft dungeons you can't pick villager as a character; all playable characters in minecraft series (not sure about story mode) are humanoids

While this may be the case, I still don't think it warrants a change to AoA NPCs. As I said, an intelligent creature can chose to trade and do nothing more, and I'm not sure its really a "rule" in the game. There is also the issue of removing the mod's unique content in favor of something less unique, but that's a debate for another day.

**Comment by HyDefier** [comment]
I think just keep making them fit the dimensional theme over anything else. It is a bit weird that all of the lottomen and masters have a player model, but most dimensions already have a cool themed trader with a custom model.
