### ISSUE TITLE
mob spawn again

### ISSUE THREAD

**Issue by rechalow** [Tslat/Advent-Of-Ascension#1760]
**Mod Version**
3.3.2

**Describe the bug**
creaponia was spawn again

**To Reproduce**
When I killed a creeponia
Then I quit the game
But when I entered the game again, I found that creeponia was spawn again
I was forced to change to creation and kill again
I have two creeponia tables
This will cause many players to die

**Expected behavior**
Players quit the game and killed mobs will not be spawn again

**Screenshots**
Sorry, I can't give pictures

**Comment by Tslat** [comment]
I'm.. not sure what you're saying here

**Comment by rechalow** [comment]
![QQ图片20200719142516](https://user-images.githubusercontent.com/61784773/87868875-330a1980-c9cd-11ea-8bcb-4e2b667bb753.png)
![QQ图片20200719142608](https://user-images.githubusercontent.com/61784773/87868882-3c938180-c9cd-11ea-8c5c-d90986aa11e2.png)
![QQ图片20200719142608](https://user-images.githubusercontent.com/61784773/87868886-4ddc8e00-c9cd-11ea-9f0e-067c0c6a0fd6.png)
![QQ图片20200719142637](https://user-images.githubusercontent.com/61784773/87868894-651b7b80-c9cd-11ea-8a48-63c4c9844e6f.png)
![QQ图片20200719142700](https://user-images.githubusercontent.com/61784773/87869038-c728b080-c9ce-11ea-875d-70880d9b9c56.png)

**Comment by masterbobli** [comment]
**Mod Version**
3.3.2
 
**Describe the bug**
The Boss C.R.E.E.P. respawns after reloading the save file.
 
 **To Reproduce**
1. Create a world
2. Spawn a C.R.E.E.P. by using the Explosive Gems on a Creep Altar
3. Kill the Boss
4. Immediately save and quit after boss is dead
5. Load the save file
6. A C.R.E.E.P. Boss with full health appears.
 
 **Expected behavior**
C.R.E.E.P. should still be dead after reloading the save file.

**Comment by Tslat** [comment]
Fixed in next version.
