### ISSUE TITLE
Lelyetia /home levitation bug

### ISSUE THREAD

**Issue by zoyer2** [Tslat/Advent-Of-Ascension#1772]
**Mod Version**
AoA3 3.3.2

**Describe the bug**
When you are in the dimension Lelyetia and levitate by jumping down, doing /home on a server, teleports you back to the overworld but gives you flight, to reset it you need to tp back to lelyetia.

**Comment by Tslat** [comment]
I'm not really sure I have a way of fixing this. I can't just assume any player with anti-gravity is from Lelyetia.
There's a hook for changing dimensions which is what I use, but server plugins/mods don't use it properly so it gets bypassed.

**Comment by zoyer2** [comment]
Ah i see, only thing i could think of is to add an effect to the player with a timer but maybe its too much to change, understandable if you won't focus on fixing it. Great mod anyway, keep it up 👍

**Comment by Hamburger666** [comment]
maybe adding a different tag for each player when they enter a different dimention?
such that if their current dimention is not the dimention of their tag stop applying any effect from the dimention of their tag and replace their tag with an appropriate tag?
or if each dimention have exactly one biome make biome tags insted of dimention tag
so that you can even make changes to vanilla biomes
