### ISSUE TITLE
Better Pickmax

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#1778]
Imo, it's not very useful. 

Lots of other mods already add tools that break multiple blocks at once or even break through larger ratios than the Pickmax and are usually much easier to obtain.

It could do one of these things (While also keeping the current ability it does now):

1. Increased chance of a Foraging drop when mining. (Helps train Foraging itself a lot quicker)
2. Increased experience from ores mined.

I also think there should be an option to mine a single block whenever you mine while sneaking for convenience.

**Comment by Cruuk** [comment]
So what if an item from another mod allows you to break multiple blocks and can be easily obtained, therefore being really unbalanced. I'm pretty sure Scimi is more interested about balancing the mod around itself rather than keeping certain "balanced" mods in mind. At this point, we've stopped caring about how OP Tinkers is.

I'd say Pickmax is still powerful on its own. With eff and unbreaking/mending it becomes an absolute machine. It already makes Foraging the easiest skill to get to 100, I know because I literally used it for that in my survival world, and it didn't take long. I really don't think it needs to make Foraging training even faster, that would be ridiculous. I had to start throwing Diamonds out of my inventory because of all the drops I was getting. I trained Foraging to 90+ just for the gold coins, and if it weren't for Pickmax it would've taken 10x longer.

Having crouch toggle the extra mined blocks would be pretty cool though.

**Comment by DiamondWalker** [comment]
Like cruuk said, pickmax is already really powerful, even if you exclude foraging with pickmax you can just walk forward while digging all the blocks directly in front of you and exposing a bunch of ore. Combined with occult pickaxe you effectively have infinite ore. It's also extremely useful for building farms and underground stuff. Other mods having better gear isn't really a good argument; you could've used the same logic to add a 500 damage sword so it can compete with orespawn and such mods.

I do like the shifting thing tho since you don't have to bring a second pickaxe to take care of the more precise mining.
