### ISSUE TITLE
am i allowed to use the textures of unobtainable things that have no use

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1836]
cuz im creating a mod and im running out of texture ideas

**Comment by Tslat** [comment]
No.

Why would that ever be a thing? What if I wanted to use those items in a future update? Suddenly I can't because someone else has already used the texture.

There's plenty of resources online for free sprites, go use one of them, or make a request on reddit or the minecraft modding discord asking for someone to help.

Per AoA's licensing (http://tslat.net/Hosting/Tslat-AoA/pages/license.html):

> All past, present, and future assets of the mod are property of the mod developer only and permission to use the assets in another mod, feature, or project is denied. This includes all source code, textures, sounds, models, and designs

And again. This github is not for chatting or asking questions. Go to the AoA discord if you want to talk. **This github is for submitting bug reports and mod suggestions.**

**Comment by Hamburger666** [comment]
my discord account is broken Q3Q

Tslat <notifications@github.com> 于2020年8月31日周一 上午9:27写道：

**Comment by EatingSilencer** [comment]
What about your discord account is broken?

**Comment by Hamburger666** [comment]
nvm i made a new account

EatingSilencer <notifications@github.com> 于2020年9月2日周三 上午9:32写道：
