### ISSUE TITLE
Underwater-based Dimension?

### ISSUE THREAD

**Issue by TheHoodiedOne** [Tslat/Advent-Of-Ascension#1849]
I think some completely underwater, more extreme L'Borean dimension would be cool, as it would give a reason to use the expedition oxygen option and it would open up some cool new underwater gear possibilities. Maybe it has a theme of super deep ocean/lava+crystals? The realmstone would be obtained by, maybe, nearly drowning in Borean? 

The realmstone could also be obtained by swimming at bedrock level in Borean? Add certain plants that give air when above them (like magma/soul sand)? I dunno, i'm just throwing out ideas here. I mainly just want something where you have to manage your breath underwater.

**Comment by Cruuk** [comment]
I personally see no need for an underwater dimension. We already have L'Borean. Yes, it has shallow water, but in general having a dim with an extremely similar theme is going to cause confusion. Already, Haunted castle and Greckon being in separate dimensions is just weird when you think about it.

It's all unnecessary, you can achieve the exact same results by doing something like making most of L'Borean's underground submerged with water, as sort of an expansion to it. The dimensions already have problems with lacking in content, adding another wouldn't fix this, but I see no downsides in adding it to L'Borean. I think more people would be happy with a L'Borean expansion that adds deep, deep water underground rather than another dimension that may lack in content, yes?

**Comment by profilename14** [comment]
I do agree that making a completely water based dimension would badly clash with L'Borean and create confusion. However, I'd just like to point out that I made an 19,000 word suggestion for a water dimension here: (https://github.com/Tslat/Advent-Of-Ascension/issues/1320). It has a unique theme from just being a water dimension, has 2 massive main dungeons that are procedurally generated each time they are visited, a dangerous seafloor with special enemies/structures, islands that can be sailed to, and many other things. It also fixes one of the main issues with water based content in general (the fact that the player moves painfully slow) by encouraging the player to wear a special armor-set that makes them swim much faster. It is not fully updated for the latest version of AOA, but I plan to redo the suggestion soon.
