### ISSUE TITLE
Spawning rules don't stop "Mob Groups" even AoA spawning rules

### ISSUE THREAD

**Issue by Terenx** [Tslat/Advent-Of-Ascension#188]
1.1.3 Tslat

"Mob Groups" is a term I use to talk about groups of mobs that spawn together, like a pack of 3 Chargers, anyways what happened is that a group of Chargers spawned near my slabs, one of them however spawned on my slabs for some reason, later I found this happened with some goblins so I knew the first instance wasn't them walking onto my slabs, later put up a wall in creative and they still spawned on the slabs with their group

To recreate, have a slabbed area and a not slabbed area, then get a "Mob Group" to spawn on the not slabbed area, if it works one or more of the mobs (not all most likely) will spawn on the slabs instead of the not slabbed area, even though slabs are not supposed to allow mobs to spawn on it period.

I expected my slabs to work right, you failed my slabs ):

Charger walked off the slabs, after all it was close, and trying to lure it back on would make me feel guilty about it, even though it already was on it, their dead now, so no luck in changing the past.

**Comment by Tslat** [comment]
This is a forge spawning issue, as forge is the decider of spawn locations, and I'm not going to double check for full blocks when forge should be doing so already.

At the very worst you'll get a couple blocks into your slabbed area. If you don't want this, slab the entire area, not just spots, since most of the time the mobs will just walk onto the slabs after spawning anyway.
