### ISSUE TITLE
Resources not obstructing toasts

### ISSUE THREAD

**Issue by legitadimc** [Tslat/Advent-Of-Ascension#2201]
**I'm playing 3.4.2**

**Describe/name the existing feature this suggestion relates to**
Resources in top right corner

**Describe the change or feature you think would be good to see**
Toasts like advancements or recipes shouldn't be covered by resources like it is with status effects (potions)

Also a suggestion:
Maybe make the resources move smoothly downwards for the toasts and effects to appear, but that might be too much.

Here's a screenshot, sorry for the low resolution. In this screenshot you can see that I need a higher level of infusion, but it isn't very clear on the first toast:
![image](https://user-images.githubusercontent.com/76429141/102765969-aef1fe80-437d-11eb-8481-ec83f3b12d3f.png)

**Comment by Tslat** [comment]
The problem with this is, Toasts go like 30% of the way down the screen, and we don't have a lot of screen space to begin with.
Moving them down becomes troublesome because then I start covering up other stuff on player's screens, and the constant moving of the resources makes it look stupid.

If I take the alternate route and make the resources disappear or fade out when toasts are there, the resources become unusable when a toast is present, which will also annoy players.

I don't think there is a good solution to this - besides just having players close the resources menu with the hotkey for it, if they're so inclined

**Comment by legitadimc** [comment]
You can move the resources to the left

**Comment by Tslat** [comment]
Then they'd be overlaying the HUD from Neat, WAYLA, WAILA, etc...

**Comment by legitadimc** [comment]
What if you make it 50% transparent?

**Comment by Tslat** [comment]
Then you wouldn't be able to read either of them
