### ISSUE TITLE
Skill requirements for bosses

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#2241]
Many skills in AOA are not necessary towards fighting all the bosses. Some can be easily ignored as they provide no benefit to the player overall.
Bosses like Smash are easily summoned and killed, but having skill requirements will force the player to wait for better loot and get them to grind for the skill levels.
For example, Clunkhead would require the player to have an Infusion Level of 50, and a Runation Level of 75.
This can stop players from getting stronger loot until they have leveled up their skills.

**Comment by Cruuk** [comment]
At least with skills in their current state, a lot of people would... *not* like this to put it lightly. AC bosses are already constantly ridiculed for being prime examples of sloppy, artificial gating behind skills that were designed to arbitrarily gate content in the first place.

And even once skills are completely reworked, it is almost always a bad idea to take something that didn't require skills before and slap on a skill requirement. Let's flashback to 2.0 AoA, where savannah mobs forced a player to have a level in a certain skill, or else they would have no chance in a vanilla Minecraft biome. Before then, there were no levels for the player to worry about. But when savannah mobs suddenly became unkillable without having a level in [skill], the design decision was enough to give us a bad name in the modding community for years.
When designing games or a mod, it's easy to manifest false problems regarding difficulty, and as a result you may force the player to do something that was never necessary in the first place. Players don't like being forced to do these types of things, especially if it was innocuously accessible in the first place.
There are many ways you can make the skills more useful without forcing them on the player. That's why there's a whole planned update dedicated to them.

**Comment by AstralScourge** [comment]
Skills suck and I do not think we should be forcing people to level them up for things completely unrelated to them, such as bosses

**Comment by AstralScourge** [comment]
The main problem is that skills are unrelated to bosses, and this suggestion seems more like a cheap way to force people to level up skills they don't want to just to fight a boss completely unrelated to the skill to begin with.

The other is that infusion and runation are both horrible in their current state and gating more things behind those would actively make the mod less enjoyable.

**Comment by AstralScourge** [comment]
Ignoring the fact that both infusion and runation are terrible and nobody likes them, the main problem is that skills are unrelated to bosses, and this suggestion seems more like a cheap way to force people to level up skills they don't want to just to fight a boss completely unrelated to the skill to begin with.
