### ISSUE TITLE
Ability to disable realmstone drop from enemies from config

### ISSUE THREAD

**Issue by DreaD4m** [Tslat/Advent-Of-Ascension#225]
I think it is a good idea for modpack developers to be able to disable realmstone drops from mobs, especially to gate progression in certain ways by making realmstone obtainable just by crafting them. The current realmstone drop system looks kinda too broad and messy to give players an impression of 'progression'.

Is there a slightly different way you think might work as well?
Mabye adding a way to access dimensions in a different way?(like making a nether portal) But I think just being able to disable realmstone drop is much better and simpler.

Does this suggestion relate to anything existing? Has it been talked about previously?
No, I don't think so

**Comment by Cruuk** [comment]
Don't think Scimi really wants to add config options that directly change gameplay.

Even then, in the past Scimi has shown dissatisfaction with the current realmstone progression, and wants to change it in the future to be something more dynamic rather than just "rare drops from common mobs".

**Comment by DreaD4m** [comment]
> Don't think Scimi really wants to add config options that directly change gameplay.
> 
> Even then, in the past Scimi has shown dissatisfaction with the current realmstone progression system, and wants to change it in the future to be something more dynamic rather than just "rare drops from common mobs".

I agree that the original gameplay is ruined, but still I think it is a nice little touch to allow players to make a different way to play a mod, thus adding replayability. To be honest, I believe the main dimension system of AoA is very clunky and strict, giving players much worse impression when the mod is played repeatedly. I think It is just a nice little option for players themselves to create new content with AoA and adding replayability. Especially in this kind of 'modpack era' where people tends to play bunch of mods together tweaked, not just one mod and then the other.

**Comment by Tslat** [comment]
Removing realmstone drops just disables access to dimensions though - how is that 'tweaking'?

**Comment by DreaD4m** [comment]
You can always add crafting recipes for realmstone using stuff like crafttweaker.

**Comment by Tslat** [comment]
If you're counting in third party mods, why not use a mod that disables certain drops?

The problem I have with this suggestion is it leads to a landslide of similar suggestions

Disable realmstone drops?
Disable weapon drops?
Disable armour drops?
Disable skills?
Disable resources?
Disable dimensions?
Disable overworld events?
Disable individual structures?
Disable certain mobs?
ETC.......

If you want to interfere with the way the mod operates for the sake of making it work for your particular circumstance, then you could use another mod to interfere with it the way you want to, rather than me hindering performance for the thousands of edge cases out there
