### ISSUE TITLE
A mind control staff

### ISSUE THREAD

**Issue by RobTheSaboteur** [Tslat/Advent-Of-Ascension#2328]
**Describe the new feature you think would be good to add**
So there are a LOT of cool fricking mobs in AOA3, Such as the knights and angels from Runador and the Web Reapers from the Abyss

I feel like it would be cool as hell to have some sort of ability to bring those mobs over to your side. The ability to tame a knight from a shyre land or an angel from Runador and to bring them back to the over world to lets say protect your base or to follow you into another dimension to fight those mobs and bosses would be cool as hell.

I feel like this could be done with a staff that uses mind and/or life runes to mind control them. Or a new special rune called a control rune that require runination 75 or up to get.

**Add any alternative implementations you think might work**

Maybe instead of a mind control staff you could use the rare gems from that dimension to tame them or something. thatd be cool.

**Include any additional background information**
I mentioned it briefly in the discord server

**Comment by DiamondWalker** [comment]
Making them permanent pets would be a bit unbalanced (and I can't think of any way you could code something like this). I also don't like adding another rune type just for this (too many already).

I do love the idea of a staff that would replace an enemy's attack target for a certain amount of time at the cost of life and distortion runes. Maybe you can right-click on an enemy with the staff to bind the staff to them for a certain amount of time (like 30 seconds) and then point and click at any enemies you want to send your minion after. You could even use this to make bosses kill their own minions.

**Comment by profilename14** [comment]
The ability to tame mobs from other dimensions is a really cool idea, but I feel like it would be a bit too large a mechanic to just throw onto a staff. Tslat suggested (just as an example though) an idea like this as a new version of the Creation skill for the skill document. "What if Creation for example was changed so that instead of being focused on summoning minions, it was instead focused on taming hostile mobs and augmenting them with abilities and sending them to do your bidding?" Doing this would open up a huge amount of options in combat (ESPECIALLY when the mob update comes around and makes mobs have whole new behaviors and abilities), and it could give the player a whole new way to fight against enemies. It has a huge amount of potential, so I feel like it would be better off as a big skill with extra stuff like augmentation rather than a single weapon's ability.

Also, this might sound kind of silly but... I'm just not a fan of taming mobs requiring mind control. It just feels kind of messed up to have your cool Pokémon companions be brainwashed slaves. I like the idea of taming mobs with various items though (which might have some progression where the player can tame stronger and stronger mobs as they level creation). It could vary between the physiology or personality of enemies, with sentient mobs like paladins requiring being bribed/hired with rare metals, or some Undead mobs seeking occult materials like Phantasm.
