### ISSUE TITLE
AoA mobs should spawn in certain Nether biomes

### ISSUE THREAD

**Issue by ilija04** [Tslat/Advent-Of-Ascension#2397]
So, Minecraft 1.16 introduced Nether biomes. So, some Nether AoA mobs should and shouldn't spawn like in:

Warped Forests: No AoA Nether mobs should spawn there, because it is the safest biome in vanilla.

Soul Sand Valleys: Skeletal Cowman should spawn there only; because it fits with the common normal Skeleton spawning.

Crimson Forest and Nether Wastes: All the others will spawn there.

**Comment by Sonicwave** [comment]
~~While skeletal cowman does seem to fit soul sand valleys more, the slowing effect will make dealing with them annoying without ranged weapons or Soul speed.~~ I also think most nether mobs (perhaps except for Scrubbies and Little Bams) shouldn't spawn in Basalt Deltas, since the terrain will make melee mobs unable to navigate to the player, and Cowmen would knock them off ledges and into lava too easily.

In addition to being a "safe" biome, Warped Forests are also a decent way to reliably obtain Ender Pearls if you don't have access to the end yet (especially with AoA mobs in the Overworld spawn pool), and having all the AoA mobs occupy the spawning pool there takes away from that.

**Comment by ilija04** [comment]
Oh, i forgot to mention Basalt Deltas.

**Comment by Tslat** [comment]
Alright
