### ISSUE TITLE
Remove the coin-based currency system

### ISSUE THREAD

**Issue by ZeroDhita** [Tslat/Advent-Of-Ascension#2419]
(Sorry for the poor English)
-Remove the coin-based currency system and switch to the vanilla emerald one.
Realy I don't see why this mod should have coins, they were one of the many feature added by the old developer that were added just to have more content in the mod, but since emeralds are already the currency in minecraft world i don't see why coins should stay.Also change the npcs trades and make them require emeralds instead of coins.
The reason to remove them are:
-A currency already exists(emeralds)
-Beside being used for trades they don't have any use
-The don't have any use for progression since realm travel ticket was removed and (if i remember correctly) no boss-summoning item needs to be bought with them (silverfoot is getting removed in 1.16.5).
-Expetialy for overworld npcs they feel even more unnecessary (e.g. why do i need to pay a silver coin (which you need to get from a a bnker in another dimension) to get 64 ancient rock from a Realmshifter ? insted i could pay him like 1 Emerald to get 8 ancient rock ?)
-They are not even usefull for modpack creators, because they are both renewable an prety common (and as I said you need to get to another dimension just to convert them to other tiers).

(I'm preaty bad at  explaining things, expecially in a foreign language, but I think you get what i mean) 
The only problem that i can see are lunaver coin trades, which might need some re-balancing, but apart for that I don't see any problem.
Oh and whithout coins bankers npcs probably needs to be removed because they became useless.
(Edit: also removing emeralds from rare table or jus chaingin ho much of them you can get (not 5-25 bt like 1-4) might be needed),

**Comment by DiamondWalker** [comment]
I think the coin system is fine. It has a lot more potential than just emeralds.

That being said, it does need some work. Perhaps making better coins be locked in later dimensions, so the whole banking system feels less useless.

**Comment by Cruuk** [comment]
You can get silver/gold coins from Overworld chests for that Realm shifter trade. Highly disagree with this, changing the trades to Emeralds just centralizes stuff to Overworld, which we're trying to avoid (coins are also less annoying to get- basic universal mob drop vs. an item you can only get lots of if you use vanilla mobs that don't spawn in the other 22 dimensions).

You can definitely improve them, but I highly disagree with this

**Comment by XxDuckyUxX** [comment]
You can get unlimited emeralds via a raid farm or villager trading hall designs in the later updates. Coins only drop in copper with most mobs and most things are sold in silver/gold. Therefore, forcing you to find a banker (or explore a new dimension). Emeralds are hard to get otherwise because you have to be in an Extreme Hills biome. 

Highly disagree with this one.

**Comment by ZeroDhita** [comment]
Ok, so:
-Emerald are overworld exclusive: this can be solved by adding emerald ores in other dimensions, also emealds could be added to universal mob drop loot table
-They are too inflacted: Maybe use also emerald blocks in themost expensive trades ? Trades already needs to be re-balanced, so maybe getting a little less ting for the single trade for a lower price like in the example can be the way.

Or maybe just overworld npcs can use emeralds ?

**Comment by Cruuk** [comment]
If we're removing "content that was added for the sake of content", then why would this change make the mod worse off?
Why should all dims have Emerald ore? Why should Emeralds be in universal drop tables? Why should trades have to be rebalanced? What would this ***actually*** add to the mod, besides making it "consistent" with vanilla? It's not always a good idea to be consistent with vanilla. We're not nerfing t1 items to be consistent with Netherite, because it'll make the whole mod worse for instance.

This is replacing "content that was added for the sake of content" with... changes that were made solely for the sake of changing.
The "consistency" with vanilla doesn't even make sense. Vanilla Minecraft has another species that trade/barter: **Piglins**. And they use gold ingots, not Emeralds.

By definition, coins are not bloat (with the exception of circus coin). They are clearly defined items with many usages. It is not our duty to bend over for vanilla and downgrade mod features to make things "consistent" with vanilla. There are plenty of other mods that add Emerald trades.
