### ISSUE TITLE
Increase damage of all weapons/scaling/better in general

### ISSUE THREAD

**Issue by Aggronfan** [Tslat/Advent-Of-Ascension#2525]
**Describe/name the item/content this suggestion relates to**
Almost all weapons added in. Melee, firearms, bows, crossbows, staffs, etc. and maybe throwing weapons.

**Describe the change/balance you think would be good to see**
More damage/better scaled weapons, and or better/fun effects (massive damage boost in water, increase damage to mobs, causes other mobs to attack the target, etc.) 
Example: Void sword (pretty easy to get) deals 11 damage, candlefire (harder to get) deals 18. Maybe 12 for void and candlefire deals 28. Mauls deal like 28 or something, so make them deal 40 or so but make their abilities good (massive aoe swings, ignore armor, etc.)
Greatblades being in general better than swords (no looting III and such is the only downside) but not by much.
Staffs especially are not good as they require runes which aren't easy to make and deal little damage.

**Include any additional background information**
Most weapons are only a bit better than one another, where a mid or early game weapon isn't far off of damage compared to endgame weapons. Especially noticeable against bosses and their massive hp pool. This could also be a suggestion for nerfing bosses as well/making them more fun to fight.

**Comment by Cruuk** [comment]
Why? Lower scaling makes it so you're not absolutely required to get the next tier of weapon, it makes it so you still have a chance with a lower tier weapon that's hard to get, even if you're at a disadvantage. Overly high scaling does nothing but appease children who love high numbers and nothing else. MC is really poorly made for high scaling, anyway. Netherite sword doesn't deal like 16 damage. Lower scaling also makes it so we fit better in modpacks. 

Consider that swords are able to jump crit, be affected by strength, and more. It's very easy to make a 7 damage sword deal 20+ damage with the right stuff. Now apply that to a sword with 18 damage.

Literally some of those abilities are already in the game, Illusion sword can make mobs attack other mobs. Have you played the mod?
Bosses haven't been rebalanced yet, that's why they're balanced terribly, when weapons have been rebalanced.

**Comment by Aggronfan** [comment]
I will be honest and say that I glazed over the illusion sword somehow so my bad on that front. I would say most of the issues seem to be the bosses and just mc combat in general so yeah also fair point. I will give it more time and wait for boss rebalances I guess.
