### ISSUE TITLE
Null Layer Render

### ISSUE THREAD

**Issue by Flamebom** [Tslat/Advent-Of-Ascension#2531]
**Mod Version**
AoA 3.5-Beta-4

**Describe the bug**
Crash on start up.

**To Reproduce**
Steps to reproduce the behaviour:
Other Mods: Mekanism
1. Launch Game

**Expected behavior**
Game should launch properly.
According to their github, it happens when adding a null layer render to an entity, which means some entity in this mod has a null layer render, and would crash if rendered.

**Comment by Tslat** [comment]
I can't work with a crash if I don't have the crash report

**Comment by Flamebom** [comment]
Hmm seems like redownloading the mod made it work again.

**Comment by Tslat** [comment]
Where are you downloading it from?

**Comment by Flamebom** [comment]
I downloaded both times from curseforge

**Comment by Flamebom** [comment]
https://gist.github.com/Flamebom/57445dcc9e73b1aee4ed2a79c97f800e

**Comment by Flamebom** [comment]
It seems like I got the error again, and by disabling AOA i don't get the error anymore

**Comment by Tslat** [comment]
Try it with ONLY AoA and Mekanism.

I don't add any null layers to entities, and in fact I don't even see how that'd work, since vanilla itself would crash if a render layer was null (See LivingRenderer line 124 & 125)

I'm wondering if another mod is trying to add something to an AoA mob or something and causing a conflict.

**Comment by Flamebom** [comment]
It worked. I also removed random patches and it also worked
