### ISSUE TITLE
Lottomen getting killed by zombies crashes the game

### ISSUE THREAD

**Issue by randomuserrnam** [Tslat/Advent-Of-Ascension#2612]
**Mod Version**
AoA3-3.5-1.16.5

**Describe the bug**
Lottomen getting killed by zombies crashes the game

**To Reproduce**
Go into creative mode, spawn a lottoman and zombie, wait until the lottoman gets attacked a few times.

**Expected behavior**
Game to not crash

**Comment by Tslat** [comment]
If you've got a crash can you upload the crash report so I can see it?
A crash you have might not be the same one that I have

**Comment by Sonicwave** [comment]
The following crash report was caused by having a Zoglin kill an NPC. So far it seems to occur whenever an NPC is killed by most entity-based sources, with exceptions including player melee attacks, TNT not lit by the player, and command-summoned dragon fireball clouds (but not arrows).
[crash-2021-06-06_17.53.18-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6605247/crash-2021-06-06_17.53.18-server.txt)
