### ISSUE TITLE
Gardencia Mob

### ISSUE THREAD

**Issue by Craexxeus** [Tslat/Advent-Of-Ascension#2676]
The mobs in Gardencia when taking fire damage deal more damage to them.

**Comment by Tslat** [comment]
What?

**Comment by profilename14** [comment]
If I had to guess based on the wording (although I could be wrong), I think they mean that Gardencia mobs should take extra damage from being on fire due to being plants. Could be a fun gameplay mechanic to differentiate fire damage from other damage-over-time effects like poison (if it can be implemented).
