### ISSUE TITLE
Emberstone tools don't smelt clay into bricks

### ISSUE THREAD

**Issue by PIXELATOR37** [Tslat/Advent-Of-Ascension#2690]
This one should explain itself. I encountered this in version 3.5.2, and thought it was significant enough to warrant a new Github issue

**Comment by Tslat** [comment]
This one poses an interesting conundrum.

The reason this happens is because clay blocks don't drop clay blocks, they drop balls.
Because of this, my current implementation ignores the drop because it doesn't know that the balls are the intended drop of the block (I have no way of knowing)

To resolve this, I'd have to allow autosmelt tools (emberstone) to smelt _all_ drops from a given block. This poses an issue with compatibility for other mods, and potentially drops for skills and other events too
