### ISSUE TITLE
Embrake's fire placing ability can delete blocks

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2757]
**Mod Version**
What version of the mod are you on?
3.5.4

**Describe the bug**
Embrake's fire placing ability can delete blocks. The code only checks if the block under the target isn't air, but it doesn't check if the block at the target's feet is air. This means if the player manages to place a block at their feet, such as glass, or dimensional fabric, and the player gets attacked by am embrake, the embrake's fire will delete the block.

In normal gameplay, this will probably most likely affect nether portals, which can be broken by an embrake placing fire in the frame.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a block at the player's feet. Make sure there is a non-air block below the player. Easiest way is to stand inside a lit nether portal (vanilla, not aoa's).
2. Spawn an embrake and have it attack you.
3. See error

**Expected behavior**
The embrake's fire doesn't replace blocks.

**Comment by EatingSilencer** [comment]
https://user-images.githubusercontent.com/44556728/126067117-d20a8f16-38c6-4bad-b0eb-e4e7d63dd5bd.mp4

**Comment by HyDefier** [comment]
Should the Embrake's fire be able to break some plants, or exclusively air? (Don't think about it too hard). I would expect it would be able to place its fire with the same conditions in which a regular player can place a block, so a block like grass would be broke, but solid blocks, slabs, portals etc which a player can place on rather than in would simply cancel fire placement.
