### ISSUE TITLE
Restocking being weird in certain ways

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2772]
**Mod Version**
3.5.4

**Describe the bug**
The exact properties of these issues are sparse, so all we have are empirical instances of restocking not working under certain scenarios. I am unsure if these 2 are related to each other somehow:

1. Restocking appears to function oddly in dims with no day/night cycle. In our testing, restocks functioned fine in dims with a day/night cycle. But in dims with no day/night cycle, it took way longer than 10 minutes for a trade to restock.

2. This is in Overworld. I exhaust a trade, I go away 24 blocks and it restocks, exhaust it again, do ./time add to speed up the 10 minutes and it restocks. But after it exhausts again, suddenly /time add doesn't work anymore when it comes to restocking. No matter how many times I do the command.

Scenario 2 seems more like the correct instance, but I could be wrong.

**To Reproduce**
Steps to reproduce the behaviour:
Read above.

**Expected behavior**
Restocking working normally

**Comment by ge9** [comment]
I observed similar behaviors too.
I'm also playing the version 3.5.4, with several other mods, in SMP.
I named (by name tags) and transported (via Nether) naturally spawned Lottomen to my home, and all of them eventually stopped restocking forever (longer than 10-20 days in the game).  Also, they restocked more frequently than twice a day before they stop restocking.  
The result was similar if I remove all other mods, switched to singleplayer, use spawn eggs (not using Nether), and/or use other NPCs.
Is there a method to make NPCs restock correctly? (is my testing insufficient?) If there is, I'll use it before the bug is fixed.
