### ISSUE TITLE
New Craexxeus AI

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#287]
I think Craexxeus is underwhelming. It's supposed to be the strongest boss, and a "superboss", but it has nothing to earn it that title aside from high HP and some semi-unique drops. Here's an idea for new AI:

Craexxeus:
He would often fire a stream of 5 consecutive projectiles towards the player. This would happen every few seconds.

Sometimes, instead of firing the stream, he would fire 5 gravity-affected projectiles at once in a vertical line, like this: ![craexxeus](https://user-images.githubusercontent.com/19913710/52319328-16c01b80-2997-11e9-9cc6-3c31f98de563.png) After doing this, he would fire 5 more projectiles at once, this time in a vertical line: ![craexxeus attack](https://user-images.githubusercontent.com/19913710/52319357-3a836180-2997-11e9-8e33-502071ccda41.png)

In another attack, he would teleport to the middle of the room, above the altar. He would hover there, and fire a constant barrage of projectiles towards for a few seconds. These projectiles wouldn't be fired directly towards the player, just in his general direction.

He could also teleport directly above you. He would fly above you, dropping down special projectiles. These projectiles would stay on the ground, chasing the player. After dropping a few of these projectiles, he would drop down, firing 8 projectiles in different directions when he lands.

Xxeus:

He wouldn't walk at all. Instead, he would move by jumping. He would use one attack at the time, waiting about 1 second after it is finished before starting the next one.

Would teleport above the player. When he touches the floor, he would leap towards the player. When he touches the ground, he will leap again. Touching the ground for the third time would end the attack.

Would teleport to any of the four compass directions from the player. After waiting a few seconds, he would leap towards the player. Touching the floor will end the attack.

He would teleport to the middle of the arena, standing on the altar. He would quickly "bunnyhop" towards the player at high speeds. After a while of hopping, he would make a large jump towards the player. At the peak of this jump, he would use the "slice" attack he currently has (the one that acts as an area of effect). When he lands, he would throw the Ancient Ring you used to summon him at the player, using it as a weapon. It would act as a magical boomerang, homing after the player for a few seconds, and the returning to Xxeus. Once Xxeus grabs the Ancient Ring again, the attack ends.

Once Xxeus reaches 50% health, he would summon an immortal "Soul of Crae". It would be a transparent, ghostly variant of Crae. It would have the same AI as the first Craexxeus phase. Once you kill Xxeus, he would also die.

**Comment by Cruuk** [comment]
The thing with the vertical and horizontal projectiles is interesting, though I feel like there should be a slightly longer interval between these streams of projectiles to still have somewhat of a focus on Craexxeus both being melee and ranged.

The things with TPing to the center of the room, and the hovering things are interesting as well. It would be a good replacement to the whole TPing player shit.

The Xxeus thing just sounds confusing to me, maybe I skimmed it too fast. I feel like Xxeus is mostly fine as he is, though maybe you could lower his walkspeed to not make him so overwhelming and to add a new attack or 2 to make up for it. I think Xxeus should be fairly simple as a boss in general, considering the Soul of Crae thing that happens at 50% hp. I always imagined Xxeus as more of a powerful blunt swordsman rather than someone who relies on gimmicks.
I do like the "Soul of Crae" thing though. I'm imagining a version of Crae without a mount and looking really similar to the Soul Scurry mobs.

**Comment by DiamondWalker** [comment]
Perhaps I did a bad jump at explaining Xxeus. The idea is that he would bounce around and launch himself towards you a LOT. Imagine all the attacks I explained happening really quickly. I also added the Ancient Ring thing because I felt it was unique to have the boss' summon item be involved in the fight in some way.
