### ISSUE TITLE
Boss Damage Changes

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#295]
Lots of bosses damage stats are to strong for 1.12, so some nerfs will be needed.

**Smash**, 15 > 13

**Corallus**, 25 > 12
- Strong Form, 75 > 25

**King BamBamBam**, 20 > 9

**Rockrider**, 35 > 17
- Range Resistance, 30 > 15

**Yellow Guardian**, 15 > 9
**Green Guardian**, 20 > 12
**Blue Guardian**, 20 > 12
**Red Guardian**, 20 > 12

**Skeletron**, 70 > 30

**King Shroomus**, 20 > 10

**Visualent**, 20 > 15

**Kror**, 60 > 30

**Dracyon** (Melee), 25 > 20

**Voxxulon**, 30 > 22
- Ranged Attack, 35 > 25

**Okazor**, 50 > 30

**Graw**, 30 > 24

**Horon**, 24 > 22

**Coniferon**, 25 > 20

**Cotton Candor** (Ranged Attack), 40 > 25

I didn't include Baroness, Tyrosaur and Mechbot because Its known how late game they are.

**Comment by Cruuk** [comment]
Most of these are way too harsh, consider that armor sets with 25-26 armor mostly put the damage reduction back to 1.7 levels (20 damage doing 2 hearts, etc.). This only stops once at 25 damage, where you take 3-3.5 hearts instead of 2.5. But then you have protection enchantments, and the fact that Erebon now gives resistance 1.

Yeah Selyan gave it before, but you can use this resistance in nearly any dimension now. Then you have the ways of healing. 

And even if 20 damage is 4 hearts with diamond-level armor, you still have the protection enchantments and resistance to bring it down.
Just having prot 3 on 1 piece of armor and resist 1 already brings it down to 3 hearts.

And of course, don't forget shields, even if it gets nerfed to like 20% protection that's still additional protection on top of everything else. The only ones that need nerfing are the ones at 35-40 damage or higher.

**Comment by Sagisolar** [comment]
I'll probably redo the damage. Thanks for mentioning tho
