### ISSUE TITLE
Have all boss spawners be reusable OR give all of them durability like Bone Horn/Mega Rune Stone

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2963]
I am thinking way too far ahead and speculating again, but I don't consider that a problem. I like being on top of things, even if there's nothing there- metaphorically speaking

Tslat emphasized being able to make structures for the bosses, without having to actually put the boss in there, for the Nowhere boss thing. This, along with giving the boss spawners the yellow rarity color, tells me he wants to make getting them a more involved process. And I think that would be good.

But lets assume the boss spawners are at the end of long dungeon structures. If you needed multiple spawners, it would be annoying to go through multiples of the same structure for the same item. I don't think it would hurt to make them **reusable** like realmstones. 
No need to prove yourself of being able to get it more than once. You still have to be able to kill the boss to get real use out of it anyway. Tslat also said he wants to make bosses more multiplayer-friendly, and it would suck to run out of spawners while boss-grinding with other players, even if only 1 person needed the spawner.

------------

If you don't like that, I would also settle for making every spawner work like Bone Horn/Mega Rune Stone, where they have a certain amount of durability and can be used a certain number of times (and can be repaired at the cost of repair dust and stuff).

I always preferred the harder to get/can be used multiple times boss spawners over the can be easily obtained/can only be used once ones. It's hard to find a substantiated reason for why, I guess I think it just flows better. It also makes the boss spawner feel more "special".

**Comment by DiamondWalker** [comment]
I'm not sure what the nowhere boss thing is, but I don't really like this idea (unless something like superbosses do end up happening). When bosses are too easy to spawn it just ruins them for me, since whether I win or lose I can just go back and try again instantly until I get past it through sheer luck. I know AoA bosses suck right now anyways so it wouldn't make much of a difference, but I can see this sucking out the tension of improved bosses.

What if, instead, bosses returned the spawn item when killed? Or better yet, have expensive boss spawns simply be deactivated after use and be recharged with some cheaper recipe? Both of those would solve your issues while not making the spawns seem so expendable.
