### ISSUE TITLE
Crash on launching

### ISSUE THREAD

**Issue by drwad** [Tslat/Advent-Of-Ascension#3131]
**Mod Version**
AoA 1.16.5-3.6.1

**Describe the bug**
Crash, i don't know hot to read changelogs so:::...
It's probably a conflict with other mods

....
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

[crash-2022-04-26_10.51.28-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8561474/crash-2022-04-26_10.51.28-client.txt)

**Comment by Tslat** [comment]
This is a Pehkui issue
He has his defaultRequire set to one, but that fails when it's run with AoA because AoA modifies the same variable first.

This variable is commonly modified by mods trying to extend reach, so he needs to make sure he overrides his require value in his mixin and sets it to -1 again
