### ISSUE TITLE
Localized translations does not display on version 3.6.4 (1.16.5)

### ISSUE THREAD

**Issue by bsdayo** [Tslat/Advent-Of-Ascension#3202]
**Mod Version**
Mod version: 3.6.4
Minecraft version: 1.16.5
Forge version: 36.2.35

**Describe the bug**
Version 3.6.3 can display the translation correctly, but the translation disappears after updating to version 3.6.4

**To Reproduce**
1. Launch Minecraft and load a save
2. Switch language to other translated languages (such as Chinese)
3. Check if the name and description of the item of AoA3 found are still in English

**Expected behavior**
Display localized translation correctly, like version 3.6.3 or earlier.

**Screenshots**
Not yet

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/76616758/168995124-c65218a2-0586-493e-92c3-6ffb98fae4e6.png)
![image](https://user-images.githubusercontent.com/76616758/168995168-5b526fd2-a9b5-46d8-ae1f-82d74d2b0c84.png)
so that's the reason
![23U8P6G@ 97`P2TZ8A4{_GM](https://user-images.githubusercontent.com/76616758/168995238-34989959-b15f-4674-8edf-5a7f55e9df6e.jpg)

**Comment by Tslat** [comment]
lol.. nice
