### ISSUE TITLE
AoA doesn't spawn mobs or Emberstone ore in non-vanilla nether biomes

### ISSUE THREAD

**Issue by Questwizard** [Tslat/Advent-Of-Ascension#3203]
**Mod Version**
1.16.5-3.6.3

**Describe the bug**
Having a nether biome mod such as Oh the Biomes You'll Go, Better Nether Reforged, Infernal Expansion, etc. seems to break AoA's mob and Emberstone ore spawning in the nether. Mobs won't spawn at all, and the ore only generates in vanilla Minecraft biomes. Strangely, structures like the nethengeic pit still spawn.

**To Reproduce**
Steps to reproduce the behaviour:
1: Install a biome mod that affects nether biome generation
2: Check for mobs, and ore in modded biomes, as well as vanilla ones. You shouldn't find AoA mobs, but should find Emberstone ore in vanilla biomes.

**Expected behavior**
Expected AoA mobs to occasionally spawn, and to see Emberstone ore in netherrack in modded biomes that have it.

**Screenshots**

**Comment by Tslat** [comment]
So this is down to BYG using the nether stone tag for ores instead of the matcher that vanilla uses

Unfortunately the tag that BYG uses also happens to count for a other blocks too, which we don't want emberstone spawning in
So while this is possible to make compatible, I don't think it'll be good for playability
