### ISSUE TITLE
Smash should disable shields

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#3369]
Smash's melee attacks should disable shields.

1. he uses an axe now, and axes disable shields

2. I'm assuming his attacks will be mostly melee

...what do you mean I should wait to see how the fight works first?

**Comment by Cruuk** [comment]
Considering Mojang is willing to break their own rules with allowing non-Axe sources of damage like Warden, I do not think it would hurt to have most boss attacks in general stun shields

**Comment by Seishan123** [comment]
I'm going to be honest... A shield just doesn't help in AoA. Way too often I'm breaking a shield because of the way defensive durability works.
It takes the total damage of an attack BEFORE reduction calculation, takes away 4 and distributes that to all armor slots randomly, or all into the shield. Overall I don't really use a shield at all after I get into a T1 dimension.
If you do include this... perhaps adding in different shields, like a limonite shield, emberstone shield ec.

**Comment by Cruuk** [comment]
> I'm going to be honest... A shield just doesn't help in AoA. Way too often I'm breaking a shield because of the way defensive durability works. It takes the total damage of an attack BEFORE reduction calculation, takes away 4 and distributes that to all armor slots randomly, or all into the shield. Overall I don't really use a shield at all after I get into a T1 dimension. If you do include this... perhaps adding in different shields, like a limonite shield, emberstone shield ec.

They're still overpowered and badly designed whether you choose to use them or not. The durability means nothing with how cheap they are, you can bring plenty of shields and/or give them unbreaking/mending. Upgraded shields cannot do anything more than have higher durability, or have an ability that makes them even more unbalanced. We in fact already have a shield upgrade (Knight's guard) with 2000+ durability, and that's all we need

**Comment by Seishan123** [comment]
I would like to point out that Knight's Guard is T4 and a greatblade as well... It's kind of overpowered but at T4 that is the point. While it can block, there is no step up to that. You also forgot about the cooldown on shields when an axe does hit them, you can change that for the type of material.
And a point on durability, I went into a Baron Castle with a single unbreaking 3 mending shield (before I ditched the shield entirely), and tharaflys nearly destroyed it in seconds. Seriously, about 8 of them, me in the corner blocking and the shield nearly went. The only reason it didn't break was because I stopped using it.
