### ISSUE TITLE
Make flying bosses in sky dimensions create platforms

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#341]
Flying bosses in sky dimensions (like Gyro or Graw) should spawn something on death to ensure their items don't fall. Gyro could summon a bounce house, and graw could maybe summon some sort of tree? To prevent griefing, the structures wouldn't override existing blocks, and would despawn after a while.

**Comment by Cruuk** [comment]
I like this suggestion, but there is one problem... You're suggesting them to **spawn** a structure on death, and that's become a taboo thing as of recently. What happens if the thing spawns on your portal? Is it gone?

Honestly just have them spawn a chest with the items on death, no need for something fancy.

**Comment by DiamondWalker** [comment]
I already mentioned the structure wouldn't override blocks and would despawn after some time. The chest thing would also be a ripoff of JitL

**Comment by Cruuk** [comment]
> 
> 
> I already mentioned the structure wouldn't override blocks and would despawn after some time. The chest thing would also be a ripoff of JitL

Sometimes I'm too wacky for my own good
