### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by AndrewthepikaDev** [Tslat/Advent-Of-Ascension#3516]
Will you add 1.18 support for this mod in addition to 1.19 support? I am making a dimensions modpack for 1.18 and want to add your mod.

**Comment by EatingSilencer** [comment]
No.

**Comment by AndrewthepikaDev** [comment]
Why?

**Comment by EatingSilencer** [comment]
AoA is currently going through a rework that will upgrade its content to make it better. But in doing this it has become caught in a bind. AoA wants to take advantage of 1.18+ features in use of upgrading content, but it can't do so because AoA's mob models are mostly incompatible with 1.18+. This means AoA can't port until its fully upgraded, but doesn't want to fully upgrade until its ported. To solve this issue, AoA is basically getting remade from the ground up, with all verisons on 1.18+ being stepping stone versions for the time being - these versions are incomplete and are missing content. It would be pointless to update AoA on 1.18 as 1.19.2+ is being worked on right now and neither version is fully playable in survival atm due to missing features. By the time AoA is fully playable in survival again, we will have likely moved on to 1.20 or beyond, and there's a chance nobody will want to add aoa to their 1.18 modpacks by that point. On another note, the incomplete AoA build on 1.19+ currently uses 1.19 features that are unlikely to be backported (e.g.: mangrove swamp features).

An AoA port for 1.18.2 was already started, and an incomplete version was released, but support was dropped when AoA was ported to 1.19+.
