### ISSUE TITLE
Dexterity Fall Damage Reduction Tweak

### ISSUE THREAD

**Issue by HyDefier** [Tslat/Advent-Of-Ascension#3518]
**Describe/name the existing feature this suggestion relates to**
In the 3.6.17 version of AoA(Dexterity should be identical in '.18), the Dexterity Fall Damage Reduction Ability as unlocked on levels 15 and 60.

**Describe the change or feature you think would be good to see**
Currently it is very easy to take fall damage by jumping down from one block ledges (or in the case of server desync no good reason at all) Fall damage reduction should apply to any fall height (remove 10 block limit), especially shorter falls, even potentially be buffed with a higher percentage reduction y-intercept for short distances.

**Add any alternative implementations you think might work**
Anything to make the system run smoother and feel more intentional

**Include any additional background information**
Could not find identical in search, is Beta feature

**Comment by Cruuk** [comment]
So the issue is fall damage taken from short heights, I.E. less than 10 blocks? Why should the 10 block limit be removed if the issue is applying to heights less than that? The 2 different abilities are for fall damage taken from under/over 10 blocks respectively. It's so at high levels, lower fall damage is mostly nullified, while higher fall damage is still reduced but still somewhat risky.

Also, the 1 block thing is a vanilla issue I think
