### ISSUE TITLE
Reverse the Gun Nerf and Bring Back 1.15.2 Guns

### ISSUE THREAD

**Issue by cerulean-2** [Tslat/Advent-Of-Ascension#3519]
Simply put, the gun system we've had since 1.16 is a _shell_ of its former self. **The damages and fire-rates for guns should be reverted back to how they were in 1.15.2.**

I would have made this suggestion a long time ago, but seeing as things are in development right now, I had thought the new gun system might be reversed of its own accord, due to the many evident problems it has.

I am aware that the Gun Nerf is a balance change. However, **during my playthrough of the 1.15.2 version, I found their strengths were just right** and fit in well with the rest of the weapons. All the other weapons were largely seen to be fine the way they were; why do guns have to suffer this unique disfigurement?

The reason people play this mod is because it's fun. They enjoy acquiring the many enigmatic weapons this mod offers. I can tell you that the guns in 1.15.2 were a lot more fun than they are now. Sure, balance is good, but the guns were balanced quite well before. This is a hard mod; it's okay to have capable weapons. **Now the guns are too weak and much less fun to use, and all without any significant advantages in the Nerf's favor.**

There are various reasons for _why_ guns aren't fun to use anymore.

The most obvious reason is, of course, that to compensate for a lower damage, the guns have a much more rapid fire-rate. However, due to the recoil after every shot, **it is very difficult to truly take advantage of this fire-rate without missing half the shots.** Before access to the Control enchantment, guns are nearly useless. Once one gets that enchantment, recoil is still a problem. In 1.15.2, you had recoil, but you had enough time between shots to adjust your aim. Now, you have to shoot slowly, but the damage is so low that you might as well not bother shooting in the first place.

After a certain point, all the fire-rates are about the same if you can't take advantage of them. **The Megagun, Minigun, and Predigun used to be special because of their fire-rates, but now they are not notable at all.**

Especially without Control, you can't do anything with the fast fire-rate; you have to shoot slowly to be accurate. So, **the guns with slower fire-rate but higher damage are disproportionately superior to the more rapid guns when they are not necessarily supposed to be.** An endgame gun whose strength relies on a fast fire-rate will not be as good as any gun with more moderate fire-rate and damage.

Next, **one needs to carry amount a copious amount of bullets.** In 1.15.2, I was already bringing around eight stacks of bullets regularly. Now, one has to bring so many bullets that guns are inconvenient for normal survival and useless for boss battles where everything you need must already be in the inventory.

It used to be easier to eyeball which guns were more powerful because the fire-rate was close to one bullet per second, and most of the statistical differences between guns was in damage. **Now, it’s harder to quickly estimate strength differences between guns.**

Also note that guns have these really intimidating names from when they were fun to use. Now, the "Flame Wreaker" is hardly going to be wreaking anything. **Guns are the quintessential Nevermine weapon; they should not be this much of a letdown.**

I get the feeling others are more complacent with these changes, but I haven’t yet seen anyone actually praising this Nerf. Even Cruuk has problems with the Gun Nerf, as he's detailed in suggestions of his own. The Gun Nerf has caused a lot of problems that didn't exist in 1.15.2; **reverting to the 1.15.2 system will fix everything.**

**Please make the guns the way they were in 1.15.2. The players would be happy, I think. I know I would be elated.**

You might say that, “Well, it’s too late. The Nerf has been in too many versions already to change it without looking foolish.” I say, the versions after 1.15.2 removed material like Immortallis and the Ancient Cavern without yet providing replacement content. When that content comes out, no one will play these awkward, development versions. **The best time to reverse the Nerf is now**, before an actual, full release of this replacement comes out, and people have proper versions they will play for a longer period.

If you do decide to follow my suggestion, I can provide a list of the old and new gun statistics side-by-side for your convenience, though I doubt you’ll need it such a list. I hope the bolded sections make reading this thing a bit easier.

**Comment by Cruuk** [comment]
Saying to fully revert something that had work put into it isn't a good way to frame a suggestion. Changes can and will be made, but you can't really suggest to do flat step-backs. Also, romanticized subjective tangents like "Guns are the quintessential Nevermine weapon" don't really add anything

Anyway, the reason it was changed because (and I asked him for these today because I forgot, assuming you didn't read the discord already) was
<code>1. Guns no longer had to be locked behind a 4-tick fire rate due to an internal change I made
2. The slower guns in particular were basically just cannons by all but name due to their speed and damage
3. Guns in general were clunky and ick, shooting in a weird rythmic fashion instead of feeling like.. guns</code>

Their DPS is the exact same still, it was just a quadruple shift in damage/fire rate. The exception to this are semi-auto guns, which have higher DPS to compensate the manual clicking. If you want something with higher base damage to hit a target because you as a player can't aim well, you use a different weapon that's better for that situation, you can't have something be effective at absolutely everything.

Guns are inherently a ranged weapon with zero movement penalty (like bows), have a cheap source of ammunition (unlike Staves), and don't have to wait to recharge (Spirit and Blasters) unless you consider running out of all ammo a time to recharge. Regardless, you can't expect them to also have high tier DPS on top of all that

The damage/fire rate paradigm guns had encroached too much on cannons- they were effectively better cannons. Cannons have lower DPS, but higher base damage to compensate, guns encroached that damage border a bit too closely, and some like Blood/Light Iron did get to a higher base damage than most cannons, but without the downside of the lower average DPS. It is a nerf to guns when used on armored mobs, but that's what cannons are for. Again, you can't expect a weapon class to be good at every role at once. Also, the higher fire rate guns like Megagun do have slightly higher DPS than the slower fire rate ones. It's a small difference, but it is there

It's an opinionated thing, but the guns feel better to fire. The older fire rate felt flaccid and again encroached too much on cannons, something that resembles an assault rifle shouldn't fire only a couple times per second. Also, Minigun and its upgrades were more "unique" because it just used a number no other ranged weapon used, and not because it's a gun that now reaches the fire rate limit and had a dedicated firing sound? Feels like were throwing the word unique around as an excuse

Haven't had issues with the recoil at all. It only becomes noticeable with minigun without control and Brace, and Brace is its own can of worms.

What did I say again? I like the change, I just think it needs improving, I just like to wait until the exact right time to be pushy about these things.

The ammo issue is known, and he does agree with that issue
