### ISSUE TITLE
Non-snipers should have a higher draw speed and less charge time.

### ISSUE THREAD

**Issue by Uknowyourbored** [Tslat/Advent-Of-Ascension#368]
**What version of the mod if this on?**
It is on v3.0.1 for 1.12.2

**Describe/name the existing feature this suggestion relates to**
All guns have an insanely slow draw speed. It is like 2 seconds until you can actually start shooting the thing. And in case of Blasters, then you have to charge it as well, which will take even longer. If you wish to even shoot the gun before the enemy can reach you, you basically need to be sniping, which means Snipers are really about the only viable option.

**Describe the change or feature you think would be good to see**
Change the gun's draw speed to the same value as swords. Roughly half the time needed to charge Blasters before firing. EDIT: Or at least the gravity blaster needs it. I see Tslat's point for everything else, though.

**Add any alternative implementations you think might work**
EDIT: Maybe a "pistol" gun type that isn't incredibly powerful (like 12 damage for the strongest ones) that can be drawn and shot relatively fast?
 
**Include any additional background information**
I've described all I could so, yeah.

EDITS: 2/25/2019

**Comment by Partonetrain** [comment]
As described in my (now duplicate) issue, this also applies to the Gravity Blaster, which will definitely cause some deaths to the void.

**Comment by Tslat** [comment]
Would this not cause guns to be completely superior to swords in pretty much every single way?

**Comment by Cruuk** [comment]
^
Also, you're really not supposed to pull it out right in the middle of combat. It's something you hold before combat, then hold it the whole time as you kill ~3 mobs or so, then take it out of your hand.

Also, guns no longer give slowness when held so you can still do all that while running around.
If you really dislike the cooldown, you can always use bows or staves, they don't have cooldowns but have their downsides (bows slowing you down, staves requiring more ammo, etc.)

**Comment by DiamondWalker** [comment]
I don't agree with all guns having this. However, gravity blaster and revolvers should.

**Comment by Partonetrain** [comment]
That's a good point, Tslat and Cruuk. However, may I suggest shotguns having a slightly lower lower initial cooldown than the other types of guns, considering you are supposed to use them at close range?

**Comment by Tslat** [comment]
Would this not cause shotguns to be completely superior to swords in pretty much every single way?

**Comment by Uknowyourbored** [comment]
^ No it wouldn't.

Shotguns have far lower durability and require ammo, and hypothetically could shoot at a decent pace. Swords have better durability and don't require ammo.

Pros and cons would be balanced, and this is about balance, right?

**Comment by Uknowyourbored** [comment]
^ Why would it be?

If shotguns shot even a little faster, swords would still have a superior DPS.

Swords have far better durability and are more cost-effective to use than shotguns.

Swords don't require ammo, shotguns do.

If you intend to do more with a shotgun attack than 1 sword strike would do, you basically have to be at sword range + 2 blocks, which with how slow the shotguns are is negligible.

Ammo crowds out the inventory quickly, whereas the only inventory space you would lose to use a sword would be if you had a backup sword.

With all these disadvantages, how can you say that shotguns would be better than swords?

**Comment by Cruuk** [comment]
> 
> 
> ^ Why would it be?
> 
> If shotguns shot even a little faster, swords would still have a superior DPS.
> 
> Swords have far better durability and are more cost-effective to use than shotguns.
> 
> Swords don't require ammo, shotguns do.
> 
> If you intend to do more with a shotgun attack than 1 sword strike would do, you basically have to be at sword range + 2 blocks, which with how slow the shotguns are is negligible.
> 
> Ammo crowds out the inventory quickly, whereas the only inventory space you would lose to use a sword would be if you had a backup sword.
> 
> Guns in general are more rare than swords. Rare weapons should be stronger or have some utility, right?
> 
> With all these disadvantages, how can you say that shotguns would be better than swords?

You forgot to mention that shotguns have way higher base damage than swords and generally higher DPS in general. Are there swords that can deal 70-100 damage at base? The sword with the highest base DPS is 40, while most shotguns are above that and some of the higher ones go up to 50.
The highest base damage of a sword is 25, while the highest base damage of a shotgun is up to 120.
You also have the Form enchantment which decreases shotgun spread a bit. That kind of damage one-hit kills most normal mobs and deals major damage to bosses.
And one little extra thing, the bigger the mob, the less you have to worry about the shotgun spread.

As I've mentioned, something like shotguns are something you want to hold before you start fighting, and something you shouldn't let go unless you need to retreat or you've killed all the enemies in front of you. Instead of just trying to hold it while right next to a mob.
(Also something like Vivo/Amplifier seem to have the same cooldown as greatblades which is actually pretty fast for a gun)

I do agree about the durability though, the durability of pretty much all non-sword weapon types should be increased.

**Comment by Partonetrain** [comment]
Fair enough, I admit I haven't actually played with the shotguns in a survival setting. 

Still, the Gravity Blaster isn't a weapon and shouldn't be treated as such.
