### ISSUE TITLE
Make Emberstone immune to Lava

### ISSUE THREAD

**Issue by SooshiGuy** [Tslat/Advent-Of-Ascension#3723]
Since it's a mineral that is found in The Nether and Netherite already is immune to Lava, it just makes sense.

Do note that since the Emberstone and Fireborne Swords does more attack damage than the Netherite, it makes Netherite Swords pointless to obtain so I will change the attack damage of either of these swords to make Netherite Sword worthwhile to obtain if I were you.

These are the items that I'm requesting to be made immune to lava:
- Emberstone Ingot
- Emberstone Nugget
- Emberstone Sword
- Fireborne Sword
- Candlefire Sword
- Emberstone Tools
- Emberstone Block
- Emberstone Lamp
- Nethengeic Callstones

**Comment by Tslat** [comment]
I don't see how this would be balanced against netherite

Currently, emberstone is positioned as a netherite alternative with better stats but losing the protection from lava and stuff
Doing this would just make it a netherite clone?

**Comment by SooshiGuy** [comment]
That's why I suggested lowering the stats to make it worse than Netherite so that Netherite will still be worthwhile if this change was added in.

**Comment by Tslat** [comment]
Then what would be the point of emberstone?

**Comment by SooshiGuy** [comment]
That was a strange question to ask, because I can think of many, It's used for staves, armor sets and the nethengeic callstone recipe.

And also, Emberstone tools can already auto-smelt so just lower the stats. The Emberstone Sword can be changed to act as a Sword which has the exact same stats as the Iron Sword, but it has a 25% chance to inflict Burned onto its target or something like that. The Fireborne Sword can just have its stats lower than Netherite since it is upgradable.

So yeah, that's the point of Emberstone.

**Comment by Cruuk** [comment]
No thanks, not interested in making Emberstone tools unviable, it would not make the mod better at all, it'll just give players less options. If it was nerfed to that much, players would not use it, and would be forced to go after Netherite, which would only get dropped as soon as they got to a T2 dim. While you may already drop Emberstone upon getting better items, the lower difference in damage and not having to go out of the way as much for Emberstone alleviates this.

Let's look at Abyss' Bloodstone sword. For Emberstone, it's 12 vs. 15 damage, and for Netherite, it's 8 damage vs. 15. Big difference

It's not even about T2, Nether won't be required to get to the other T1s, and there are other T1 swords. Will those have to be nerfed for poor Netherite too? It would create a bigger gap between T1 and T2 swords.

Netherite armor is solid and can contend with other T1 armors along with having its own "ability", the items are immune to burning, and the ingot has usages with other AoA items, and that's good enough. The tools being weak is tough luck, the modern balance of the mod was established before Netherite was added. 

If you really want a reason to get the Netherite tools, you can add a usage with some endgame item, but I don't want something to be brought down just because vanilla has a different idea of balancing. There is no benefit to kneeling to what vanilla considers endgame in this context

**Comment by SooshiGuy** [comment]
... I am confused...
