### ISSUE TITLE
Bring Back Portal Text

### ISSUE THREAD

**Issue by cerulean-2** [Tslat/Advent-Of-Ascension#3781]
In older versions of the mod, there was a line of text that accompanied the activation of any of the Nevermine portals.

For example, activating the Haven portal would produce the text, "The light from the Haven nearly creeps through the portal."

In tandem with each portal's activation music, this feature added character and atmosphere to each dimension, and it provided a sense of anticipation, excitement, or even dread for the adventurer about to enter the dimension. This was especially true when the player had never been to that dimension before. The portal texts encouraged the player to imagine for himself what a dimension might be like before even entering.

In addition, no other dimension mod that I know has this feature, so this made Nevermine unique.

So, I request that the portal texts be readded. Is there some reason that they have been removed? It's not like this feature was inconveniencing anyone, and it shouldn't be too hard to port over between versions.

**Comment by Tslat** [comment]
It's cringey and immersion breaking?

**Comment by cerulean-2** [comment]
It's hard to argue on subjective points like that, but maybe some sort of poll would determine if other players feel the same way.

**Comment by cerulean-2** [comment]
A configuration option, with the text disabled by default, would work.

**Comment by EatingSilencer** [comment]
I disagree with it being cringey. Not sure what is immersion breaking about it.

**Comment by Cruuk** [comment]
> I disagree with it being cringey. Not sure what is immersion breaking about it.

That kind of narration telling you how to feel just doesn't work in MC. It falls in line with similar removed lines like the NPC never mine puns or the Gardencia water pressure stuff. Ever heard of show don't tell?

It's a very artificial way to build up "immersion" - even if that word means different things to everyone. If I'm in Dustopia and the chat suddenly says "the sky darkens with despair", I'm not gonna feel "immersed"

The portal sounds can stay, but a dim can bring about its "immersion" by actually being wellmade. Nowhere is immersive without needing text

In fact, we already text for the purpose of flavor: Advancements. The chat messages would be kind of redundant with advancements. We also still have bestiary entries/torn pages for more flavor

**Comment by cerulean-2** [comment]
Then a config option would be perfect. You can leave it disabled if you dislike it.

**Comment by Cruuk** [comment]
> Then a config option would be perfect. You can leave it disabled if you dislike it.

Been discussed in the discord, won't happen. Adding configs for every little thing people want tweaked quickly becomes a slippery slope

Do let me emphasize again that textual immersion never went away, only that specific instance did. Advancements and other things fill the same purpose really. Going into Precasia and seeing the "A Land Lost In Time" advancement seems pretty immersive to me.

Re-adding these specific chat messages would be redundant with advancements. We could theoretically add advancements that serve the same purpose as the chat messages, but that would be excessive since there's already advancements for getting the realmstone and entering the dim
