### ISSUE TITLE
[1.12.2] Unsafe Deserialization Vulnerability

### ISSUE THREAD

**Issue by jbredwards** [Tslat/Advent-Of-Ascension#3835]
More information can be found [here](https://github.com/dogboy21/serializationisbad#readme), the two classes in question are the following:
- [PacketIndividualLeaderboardStats.java](https://github.com/Tslat/Advent-Of-Ascension/blob/1.12.2/source/common/packet/leaderboard/PacketIndividualLeaderboardStats.java)
- [PacketLeaderboardStats.java](https://github.com/Tslat/Advent-Of-Ascension/blob/1.12.2/source/common/packet/leaderboard/PacketLeaderboardStats.java)

**Comment by Tslat** [comment]
They have a patcher in that readme that you can use

**Comment by JohanniklasLp** [comment]
There are people who do not know about the vulnerability and/or the patcher, or don't care, or cannot use any of the patchers due to whatever issue (for example some mod that breaks the patcher or that the patcher is broken for, eg (at the time of writing this) immersive aircraft), which means that they will not have the patcher's protection. Is there any actual reason for not just fixing it?

**Comment by Tslat** [comment]
You should be using the patcher _anyway_, to try and catch any unknown ones you haven't thought of or don't know about

That being said

The issue is only vulnerable for people playing on a server with the 1.12 version of aoa specifically, and any attacker has to have targeted aoa specifically as a vulnerability point, for that specific server

1.12 is a very old version, and the dev environments barely even work anymore. Releasing a version now has a whole host of problems attached with it, and this issue is easily rectified by using an already-existing tool, that people should be using anyway if they want to be sure
