### ISSUE TITLE
How about making mineralization station and bankers accessible in overworld?

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4109]
Coins are important resources.
In older versions, player must go to other dims to find mineralization station and bankers, which play important roles in obtaining coins.
But the activities like getting coins, purchasing lottos, begin in overworld.
If they can be found in overworld, the survival procedure may be more resonable and easy.

**Comment by Cruuk** [comment]
No. I don't think more stuff should be moved to overworld at all, especially since it's not urgent for these things to return at the moment.

As it stands you don't need gold/lunaver coins, and you can obtain copper/silver just fine for Lottoman/Undead herald/Assassin trades.

Assuming they'll still be in the same places, Minerlization station/some bankers are in T1 dims, I.E. the dims that will happen the soonest. There's no need to shift things urgently

**Comment by Posatasa** [comment]
Before writing this issue I also realized the statement that "push away from the overworld".
My consideration was mainly based on that the mineralization station and the bankers can help player obtain many coins quickly in overworld, which is much quicker than looting swords, it may bring some convenience.
Player can obtain enough coins for utopian armor, for magic repair dust, for limonite bullets... Mainly from a practical perspective.
Just some personal considers. Maybe when Barathos is implemented I will find the mineralization still easily-accessible, or find bankers easy to find with Lelyetia. Anyway it depends on you.
