### ISSUE TITLE
Balance/rarity issues

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4174]
I've been playing this world for about 7 hours total. In this time, I've gotten the following:
Level 18 dexterity
Level 10 extraction
Level 19 farming (mostly from farming cows and wheat to get an enchantment table)
Level 2 innervation
I haven't started training any of the other skills.

I've collected about 200 pieces of limonite, and about 80 pieces of jade. For reference, I don't think I've gotten more than 40 pieces of iron, and maybe 1 or 2 stacks of coal.

I have yet to see any underground mobs other than a single void charger that came out of a cave and attacked me on the surface.

------------------------------------------------------------------------------------------------------------------------------------------

Personally, level 18 dexterity when I haven't even gotten to the nether seems like a lot. Extraction and farming might be fine since those aren't things you're doing 24/7.

The limonite and jade spawn rates seem way too high, especially when you consider they make better gear than their vanilla counterparts and have fewer uses. Jade should about as common as runium is right now. Not sure what could be done for limonite; maybe limit it to lower y levels?

The underground mob spawn rates should be way higher, maybe even as high as they were way back before 3.2. I can't imagine how long it'd take to get void armor the way it is right now. Also, given that they only spawn way down at the deepslate layer, I feel they should be a much bigger threat than the vanilla mobs. imo it'd be cool to force players to prepare themselves with iron gear before going deeper.

The surface mob spawns seem perfect the way they are now. You can definitely see the mobs, but it still feels peaceful enough during the day.

**Comment by Posatasa** [comment]
tbh, dexterity is the slowest to train, only leads at the begining

**Comment by Cruuk** [comment]
Dexterity is a passive skill that provides a smaller overall boost compared to other skills, so it going up fast isn't a big deal practically. It slows down after 50, and especially goes up quickly if you crit a lot. I kind of want to change the passive exp rate again, but only if we get more non-passive exp methods (like Dryad sprite) so it doesn't get grindy.

What biome did you find the Jade in. It's frequent under beaches and rivers, but is otherwise slightly rarer than Diamond. Keep in mind that the OW ores (Limonite especially) are base materials that will have to be consumed often, with OW-level gear that isn't always objectively better compared to vanilla stuff, so it would just be annoying if they were arbitrarily rare. Jade being Runium-rare would be extremely overkill. A mod that wants to focus on dims shouldn't make important OW progression slow.

Dim ores will probably be more rare to make up for it, though Skeletal is frequent if you know what you're doing LOL. Not a big deal though.

What difficulty did you play on. World difficulty influences AoA mob spawn frequency, including underground. Maybe Ghost/Void walker can get their weights increased again, but it's otherwise not a goal of the mod to overtake any part of the OW - underground is already a difficulty increase with the higher quantity of vanilla hostiles in big caves. 

"Forcing" players to get Iron gear is a hard thing to enforce, players play at different playstyles and skill levels. It would especially be weird to enforce that on a part of the T0 dim

**Comment by DiamondWalker** [comment]
> What biome did you find the Jade in. It's frequent under beaches and rivers, but is otherwise slightly rarer than Diamond. Keep in mind that the OW ores (Limonite especially) are base materials that will have to be consumed often, with OW-level gear that isn't always objectively better compared to vanilla stuff, so it would just be annoying if they were arbitrarily rare. Jade being Runium-rare would be extremely overkill. A mod that wants to focus on dims shouldn't make important OW progression slow.

Was mining in a jungle. I can get why limonite would be common since it's used for ammo, but jade is only used for a few weapons/armor sets, most of which only need about 2 pieces. You can make all of those items with just 25 jade, and most of them also require stuff from other dimensions, so by that point you've probably done a lot of overworld mining and have tools that make mining more easy.

> What difficulty did you play on. World difficulty influences AoA mob spawn frequency, including underground. Maybe Ghost/Void walker can get their weights increased again, but it's otherwise not a goal of the mod to overtake any part of the OW - underground is already a difficulty increase with the higher quantity of vanilla hostiles in big caves.

Hard mode.

> "Forcing" players to get Iron gear is a hard thing to enforce, players play at different playstyles and skill levels. It would especially be weird to enforce that on a part of the T0 dim

Fair points. I've just always thought deepslate layer should be a little tougher. There's no reason to ever stay in the regular stone layer unless you're specifically looking for coal.

Mostly I'm just worried some people will get through the game without ever noticing the cave mobs exist lol.

**Comment by Posatasa** [comment]
> but only if we get more non-passive exp methods (like Dryad sprite) so it doesn't get grindy.

What about the parkours in Nowhere giving dexterity exp? A sudden idea.
