### ISSUE TITLE
The tiers materials of weapons and armors 

### ISSUE THREAD

**Issue by gjjtea** [Tslat/Advent-Of-Ascension#4181]
Some weapons and armors have useful abilities, but are often ignored because of low stats, e.g., void sword.

We can add some materials that can be applied to weapons/armors. These materials own have tiers, can increase the stats of weapons/armors of previous tiers to the level of their own tiers, and can be obtained by defeating bosses or completing some tasks of same tiers.

This will bring the following benefits:
1. Weapons/armors in low tiers can still be useful in later stage.
2. Can help make the difference of tiers more obvious.
3. Can get to make more useful abilities of weapons/armors.
4. If we try to make some weapons/armors of lower tiers still useful in later stage, their stats/abilities will be obviously stronger than others in same tier. This method can help avoid this.

**Comment by Posatasa** [comment]
Some weapons and armors have useful abilities, but are often ignored because of low stats, e.g., void sword.

We can add some materials that can be applied to weapons/armors. These materials own have tiers, can increase the stats of weapons/armors of previous tiers to the level of their own tiers, and can be obtained by defeating bosses or completing some tasks of same tiers.

This will bring the following benefits:
1. Weapons/armors in low tiers can still be useful in later stage.
2. Can help make the difference of tiers more obvious.
3. Can get more useful abilities of weapons/armors.
4. If we try to make some weapons/armors of lower tiers still useful in later stage, their stats/abilities will be obviously stronger than others in same tier. This method can help avoid this.

**Comment by gjjtea** [comment]
My browser automatically translates the content. I'm sorry! 😢😢😢
