### ISSUE TITLE
Remove the world tables

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4405]
This might be a little controversial.

If I'm not mistaken, world tables were added in 3.2 as a bandaid way to make every mob useful to some extent. This was back when the mod was still just "kill mobs for gear". However, with the new reworks the mobs already stand out on their own. This means the world tables don't have anything but downsides:

-they don't make sense thematically. You get thorns from killing a bug? Portal blocks from killing a skeleton? Some kind of alien beeswax from giant animals???

-they don't encourage engagement with the dimension. Just walk in and kill a few random mobs. They could arguably be considered free items from just spending a while in the dimension. Compare this to, say, blaze powder in vanilla. You don't get blaze powder just from walking into the nether and killing whatever's next to your portal; you have to look for a fortress, go through it, and grind a few blazes. It's much more exciting.

-minecraft isn't a "kill random enemies for loot" game. Notice how most things in vanilla don't actually involve hunting mobs, but rather farming, mining, exploring, etc. Now, I know AoA isn't vanilla, but it's still a bit weird that all the important weapons and armor and stuff is made from random mob drops when the dimension reworks seem to be leaning towards more unique things to do in each dimension (like taming the opteryxes).

Now, you might be thinking that replacing this system would be too difficult, but it'd actually be really easy, especially now that the dimensions are being reworked. Just take the global crafting materials and give them a more interesting obtainment method. Jungle thorns could come from some rare plant, making you explore the different precasia biomes until you find it. Hive chunks could come from some underground hive biome that you have to find.

EDIT: I should clarify that using global loot tables for upgrade kits is fine imo.

**Comment by Tslat** [comment]
> If I'm not mistaken, world tables were added in 3.2 as a bandaid way to make every mob useful to some extent

You are mistaken
It was not and is not a bandaid, nor was it done to make every mob useful. It was done to give every kill the chance to be rewarding, regardless of who it comes from, giving that feeling that people enjoy when they get a rare drop, even if it's a moderate one.

I won't comment on any of the other points here, just clarifying on this one

**Comment by Cruuk** [comment]
I think they're fine.

I'm not overly concerned with the thematics of it to that scrutinized extent. When we try and logic it out to that level, you can ask all sorts of things of what vanilla does and stuff. I don't want gameplay to be inhibited because it may "not make sense".

I assume you're referring to Hive chunk with that last part. That one's a bit funny, because it's actually the only dim mob drop **not** in a world table (going by 1.16 Barathos). It's only dropped by Arkback, emperor beast, nospike, and tharafly. I don't 100% know if that was intended.

-------

On a surface level, I think it does inherently encourage engagement through at least needing to kill hostiles that may be dangerous. You can alleviate the danger in many ways, but MC is inherently like this. But importantly, this point doesn't see the full picture:

Most weapons/armor require more than the world table, usually the ingot/gem. On top of getting the world table drop, you still need to find ore or loot a structure to find the ingot/gem, or any other item the weapon/armor may need. Sometimes getting the ore doesn't take very long, but hyperfocusing on the amount of time and making sure it's just hard enough can be a slippery slop for grind.

For specific examples, most Nether items also need Emberstone, which encourages you to explore the vanilla structures or mine. Same for Precasia, you also need the bone ores rather than just jungle thorns, which encourages you to go underground or loot hovels.

------

Maybe that's what vanilla MC is, but we're not vanilla MC. Also, this is a mob looting-centric mod, but this point is leaving out a lot of things.

You already mentioned Opteryx, but there's also mining, farming, exploring for things like atter nests/hovels/ashfern/loot chests in general, using brush on the suspicious gravel in Precasia, jungle thorns also being in Precasia's hauling table, and more like Arkback's whole process. Hopefully the remaining skills can allow more dim stuff.

Even now, there's still many ways to get things than only mob drops.

------

I see what you mean and I think it's reasonable, but I don't think making the world table drop arbitrarily more annoying to get is the right angle to go. If we wanted to segment the weapons/armor to be slightly less "global", we could just change other parts of their recipe while keeping the world table item a global reward. 

E.G. Raw giant lizard meat could be added to specific Precasia items, etc. It would line up with how crafted items are made up of a small quantity of different item rather than a large quantity of 1 item.

Also, I don't think it's bad if a dim has easy items, as long as it also has hard items. Easy items being most crafted stuff, and hard stuff being the out-of-the-way boss spawners and other stuff like Opteryx/Nature and Amber staff, etc. I don't think it would be very fun if even a dim's most basic equipment was annoying to get. The low damage curve also makes it so its accessibility isn't an issue.

------

Also it's not just the upgrade kits, the world tables are still important for copper coins and the rare table

**Comment by DiamondWalker** [comment]
> Also, I don't think it's bad if a dim has easy items, as long as it also has hard items. Easy items being most crafted stuff, and hard stuff being the out-of-the-way boss spawners and other stuff like Opteryx/Nature and Amber staff, etc. I don't think it would be very fun if even a dim's most basic equipment was annoying to get. The low damage curve also makes it so its accessibility isn't an issue.

Just to be clear, it's not about the items being easy to get; it's about it feeling barebones. It kind of reminds me of the souls from divine RPG: random crafting material systematically dropped in every dimension for no reason other than gating stuff behind said dimension. Obviously the AoA dimensions have more stuff than the twilight dimensions, but the crafting materials specifically basically work the same.

When I'm playing a game like minecraft I prefer to have specific goals: "hunt this mob", "mine that ore", "look for this structure", "get this enchantment", etc. "Kill random mobs until you get enough items" isn't a very clear or interesting goal to me, especially when you have it in almost every dimension.

**Comment by Posatasa** [comment]
mechanic of world table has changed already in 1.19.2-3.6.16

**Comment by DiamondWalker** [comment]
> mechanic of world table has changed already in 1.19.2-3.6.16

What does this mean?

**Comment by Posatasa** [comment]
Now world table is not in mob's loot table, every hostile mob will drop the world table when in the dimension.
So now mob loot and world loot are separated, they won't affect each other.
