### ISSUE TITLE
Nowhere death screen/animation

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4411]
I'm not sure how you'd go about implementing this, but this is a pet peeve I've had with nowhere for a while.

In basically every game out there, your character has some kind of death animation and/or game over screen. In nowhere though, you just suddenly show up back at the lobby and get a small message saying "You Died". It's very awkward.

First of all, it's confusing. When a creeper blows you up, for example, you hear the explosion and see that your character was launched. There's also the death message. In nowhere, there's often no way to know exactly what killed you. Was it a projectile? An explosion? If you don't see the thing coming directly at you before you die, you have no clue what happened. Several times I've been fighting a boss, thought I was doing well, and suddenly showed up at the lobby (guessing I got hit by an extra high damage attack) and wondered wtf happened. There's also times I've accidentally moonwalked through the exit portal because I didn't have time to react to the fact that I died and kept walking backwards lol

The other thing is that it feels jarring. You've got adrenaline pumping, epic battle music playing, and suddenly it all just... stops. The whole situation changes in such a sudden and odd way.

Finally, it just seems unpolished? idk about other people, but games have conditioned me to expect something fancy when I die. The fact that nowhere _doesn't_ do anything makes it seem unfinished.

Again, I'm not sure what exactly you could add to fix it. Maybe something like the Hollow Knight Godhome death animation (https://youtu.be/2IrAFDNH5og?t=4136), with the player being levitated and releasing particles as the screen fades out before fading back in at the lobby area? Or maybe you could change it so that you die the way you normally do except you keep your items and respawn in the lobby area. Dunno if that's possible.

**Comment by Tslat** [comment]
This isn't really possible or practical from a gameplay or technical perspective

The reason it happens the way it does is because I have to __prevent__ you from dying, in order to avoid on-death effects being triggered
This means that you actually never die, and never get the death screen

Because of that, your character is also never in the death state, and so doing the death screen isn't really possible or practical.

Doing some sort of delay/animation on death poses its own issues, as because you are still alive, everything in the world around you will still react to you (including bosses attacking you, etc..)

It more or less has to be the way it is, unless I want to spend a bunch of time on an alternate system for minimal gain
