### ISSUE TITLE
Pouches for ammo and runes.

### ISSUE THREAD

**Issue by centhusiastx2** [Tslat/Advent-Of-Ascension#559]
**Describe the new feature you think would be good to add**
Although I know rune pouches used to exist, I like the concept. And as a matter of fact, I would like to see it in ammo for guns and archerguns as well!

**Add any alternative implementations you think might work**
Or maybe an inventory option for putting ammo and arrows in a certain inventory space. (For example: Galacticraft's oxygen armor input, Baubles inventory space)

**Include any additional background information**
It relates to the rune pouches, and I don't think this has been talked about before.

**Comment by Tslat** [comment]
Most definitely has been talked about before.

**Comment by Cruuk** [comment]
Guns, bows, archerguns, and staves are balanced around the fact that ammo takes up inventory space. The rune pouch was removed on purpose. Adding a pouch for ammo/runes would mess up this balance. Energy weapons would also suffer since a big part of them is that you don't need to have ammo in your inventory for them.
