### ISSUE TITLE
Ability to set skill levels with Commands

### ISSUE THREAD

**Issue by VoidSorc** [Tslat/Advent-Of-Ascension#568]
I would like to see the ability to set skill levels with commands, either via adding levels/xp, or setting the level of the skill in question. An optional parameter for minimum skill level to give the xp would be nice. Yes skill crystals exist, but do not offer anywherei near the same level of control.

**Comment by Cruuk** [comment]
Scimi has stated that he does not want to add commands to level up skills.
I believe his reasoning for it is that he doesn't want servers to give it away or something, whether it's locked behind some P2W paywall or something.

---------------------

But you know, I've been questioning that for a while. Really, what makes AoA skills different from something like the infinite mana pool from Botania, a creative-only item that has become an endgame survival item in some packs. You can probably also get it for $10 on some shitty server somewhere.

What makes it so different from the uber-powerful endgame Avaritia items. I've heard those take a *damn* long time to get, and I'm sure some sketchy servers allow you to get it instantly for like $50.

I can understand the concern, but I'm starting to not be so sure it really justifies hindering the testing of skills at a high level. Skill crystals are reliable, but then you have shit like Expedition which take a while to reach 15, and even then holding/rapidly clicking those giant skill crystals to get all the way to 100 will take time.

In case you didn't know Void, you can also level skills by editing the NBT file or something. I'm not too familiar with it.
But why? Why should I have to learn how to do that? That sounds annoying. What's stopping a server from saying "hey man give $20 and I'll edit the NBT to give you level 500 Vulcanism". That's even more sketchy but I'm sure someone will fall for it.

Really I just don't understand why it has to be a complex process because of the worry that shitty servers will take advantage of it, when certain ones already do with endgame OP items from other mods. What would make that so different from "$40 for infinite giant skill crystals". It's like if even in creative mode you couldn't spawn diamonds/diamond tools and you still had to find those things in creative mode.

Sorry for putting this on your suggestion Void, skill command suggestions have earned a bit of notoriety for being denied and I saw this post and I just decided to let it all out.

**Comment by VoidSorc** [comment]
Modifying nbt on players is something I have a great deal of familiarity with, but it is unlikely it will fly in a modpack, or even if there are any existing implementations for nbt editing like that. I have thought of ways to do it without commands while still having access for developers, however the only way I have thought of is straight up craft tweaker integration, such as an extended IPlayer with functionality to modify the aoa stats.
