### ISSUE TITLE
Dungeon Keeper selling breakable Immortallis blocks

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#63]
**Describe the new feature you think would be good to add**
The Dungeon Keeper should trade breakable versions of Immortallis blocks so players can use them for building. They should be relatively cheap in order to allow for players to buy multiple, but expensive enough to require players building medium-size structures or larger to make multiple runs.

As Cruuk pointed out the token trader sells a lot and the dungeon keeper sells virtually nothing, and "dungeon keeper" makes more sense for an NPC selling blocks from the dungeon.

Archaic Tiles:
-Normal (1 token -> 16)
-Square, Rectangles, Horizontal Stripes, Vertical Stripes (1 token -> 12)
Archaic Dirt (1 token -> 16)
Archaic Ladder (1 token -> 8)
Archaic Glass (1 token -> 8)
Archaic Lamp (1 token -> 4)

**Add any alternative implementations you think might work**
Not really. Was thinking of a separate NPC but then I realized you can just add trades to existing ones without screwing things over (at least in earlier versions I think you could).

**Include any additional background information**
Not much.

**Comment by Cruuk** [comment]
Actually I think it would be better if the Dungeon Keeper NPC sold the breakable blocks. Token Trader already has plenty of stuff to sell (like all the vulcane augments!), so adding more would make it annoying to scroll through. Dungeon Keeper on the other hand only sells 2 things

Also I feel like it would make a little more sense for someone named "Dungeon Keeper" to sell the blocks rather than someone named "Token Trader".

**Comment by Immortallis1** [comment]
Yeah you're actually right
