### ISSUE TITLE
Nerf the flying melee mobs

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#654]
Creepird, construct of flight, flye, etc. lock onto you from several blocks away (much further than pretty much any other mob) and then fly straight at you except when you're looking directly at them in which case they have a decent chance to just retreat so you can't hit them with melee.

Because of this it is VERY common to have 5+ of these tailing you without you intentionally trying to gather them if they spawn naturally in that dimension.

**Comment by Cruuk** [comment]
I think the main issue with flying melee mobs is just how tenaciously sneaky they are. No matter how many you kill, there will always be more that spawn, and they will continue to endlessly watch you until you focus your attention on something else for a second, and when that happens they'll swarm you.

I swear, no matter how much I pay attention to them, and no matter how far away they are, I look away for seconds and suddenly they are already hitting me. I'm kind of being hyperbolic but it has really felt that way.

Not even mobs like Anemia are this persistent anymore, they still seem to have decent vision but you actually have to be in the general vicinity to aggro them. But with the melee guys it seems like they have omni-vision. In the first 3 seconds I entered Creeponia there were already Creepirds right next to me, same goes for Tharaflies in Barathos.
They don't even aggro onto ranged mobs that accidentally hit them.

I think the main things that need to be toned down are vision and maybe top speed. I'm not sure what their exact vision values are, but every flying melee mob in the general area shouldn't aggro to me the second I enter a dimension.
Their speed is fine when you're fighting them, but when you're just trying to run away you cannot get away from them unless you run around blocks to slow them down, even then running around is just gonna aggro more.
I'm not sure about this one because the speed does make flying bosses like Dracyon/Visualent a little more interesting. Hopefully mob update will make the flying melee mobs have different speed values.

I really really like the new flying AI but damn it feels like I'm always under constant stress with dealing with these things.

**Comment by Immortallis1** [comment]
Yeah that's exactly what happens. They're possible to outsprint but barely which makes them disproportionately more deadly without powerful armor, and disproportionately more annoying with it.

**Comment by Sagisolar** [comment]
Nightfly should not be changed

**Comment by maladaptly** [comment]
Fungats pretty much ruin the Mysterium. Even when in a village or on the portals platform, it's impossible to get more than about six seconds of breathing room. By the time you've killed one, 2-3 more have found you.

I should be significantly ahead of the curve; I have a cheesy Tinker's Construct shuriken build that does ~11dmg and has infinite ammo, and I'm abusing a TC6 heal focus (OP as hell) and Thaumium Fortress armor. I doubt this is the kind of power level Tslat had in mind when balancing the Mysterium, yet the only thing I can accomplish there is combat, combat, and more combat.

Mob spawn area begins 24 blocks away from any player. Most mobs aggro within 16 blocks, sometimes less. I've seen fungats aggro at least three times farther, which would be about 48 blocks -- *their aggro range overlaps with their spawn range*. This should be upgraded to an outright bug; that *can't* be intentional.

Nightflies don't seem to exhibit this issue. Actually, they're really weird about aggro in general. Sometimes they've continued wandering even after taking melee attacks. Flying aggro checks may be bugged out in general.

**Comment by Immortallis1** [comment]
Yeah it's more of an annoyance for me. With my gear they can barely touch me but when there are five attacking you at once it's just not fun

**Comment by Tslat** [comment]
There's been adjustments to flying mobs a couple times now - re-raise this issue if you think it's still a thing after 3.3
