### ISSUE TITLE
Make AoA items spawn in chests

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#746]
I think AoA items should spawn in chests. Each dimension's chest could contain items from that dimension. An example list for overworld, nether, and lunalus could be:

Overworld:
Limonite ingots
Amethyst
Jade
Rosite
Sapphire
Lyndamite armor
Void gear
Wind runes

Nether:
Emberstone gear (including embrodium armor)
Fire Runes

Lunalus:
Lunar ingots
Lunar gear
Observing Eye
Lunar runes

Of course, there would be more items in the loot tables, and each dimension would have their own. Also, this is based on the fact that (afaik) there will be dungeons with chests in most dimensions.

**Comment by MechanosG** [comment]
I'm personally against this idea.  This would reward players that rush villages (and anything else that spawns chests), which would encourage players in servers to constantly spam worldgen hoping to bypass the current mining and progression.  A trend that already plagues many mods.  It would get worse when AoA is used with other mods too (especially mods that give you faster travel or can detect dungeons or spawn extra structures with chests).

I would suggest the opposite.  Less reliance on dungeon loot tables via some way to craft (or loot from enemies) what's currently found in them, such as portal runes, so that people can progress without having to spam worldgen and potentially lag servers.

I feel loot chests are better for things not important to progression.  Rare collectables, banners, etc.  Stuff that would be neat to find, but not worth traveling 10000 blocks for.

**Comment by Tslat** [comment]
Done
