### ISSUE TITLE
Change blood color for certain mobs

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#884]
I'm pretty sure bloodlusts are meant to be blood drops, but a lot of mobs in both vanilla and AoA look like they wouldn't have red blood. My suggestion is to make bloodlusts have a color value that is red by default, but a different color if they are spawned from a specific type of mobs. He few examples are:

Creeper-styled mobs = grey
End-styled mobs = pink
Fire mobs = orange
Deeplands mobs = yellow or black
Vox ponds mobs = brown
Barathos/alien mobs = dark purple/blue

It'd also be nice if undead mobs didn't spawn bloodlusts, for obvious reasons

**Comment by EatingSilencer** [comment]
As cool as this would be, FYI I think its been confirmed that bloodlusts aren't actually blood.

**Comment by Cruuk** [comment]
Not a bad idea, but it doesn't feel too intuitive. Players may see different-colored Bloodlusts as completely different things rather than just an aesthetic thing. It doesn't help that another skill (Infusion) has different-colored sparkly things that *do* have different properties (level reqs and infusion stone), further adding to the confusion for newer players.

Also no thanks to making undead mobs not drop Bloodlusts. That would be annoying, to be frank. Maybe certain mobs would have different chance to spawn Bloodlusts, but Bloodlusts in general should be a universal thing. Sometimes it's better to go with good game design even if it may not "make sense". Like greatblades not dealing vanilla critical hits because they would be really really powerful otherwise. (they still have rage crits and extra range though).
I guess it would "make more sense" for undead mobs not to drop them, but it would make the gameplay just a little more annoying, and I don't want that.

**Comment by Tslat** [comment]
Likely wont' happen for the intuitive reasons provided by cruuk above.
Also bloodlusts aren't blood, they're the essence of bloodlust
