### ISSUE TITLE
Vanity crowns for translators

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#906]
**Describe/name the existing feature this suggestion relates to**
Vanity halos.

**Describe the change or feature you think would be good to see**
See, the vanity halo thingies should probably be for translators as well. After all, aren't these called 'contributor crowns' in game or something like that? It'd make more sense for translators to have them: they physically and directly contribute into the mod, unlike donators and wiki helpers (not that I'm saying those shouldn't have crowns)

**Add any alternative implementations you think might work**
I guess translators could get some other kind of reward, but they at least need some recognition.

**Include any additional background information**
Talked about it previously in the discord, idk if there was ever a suggestion here

**Comment by Tslat** [comment]
The main reason I haven't done translator halos is because they're more or less permanent.

All the other halos symbolise a continued contribution to the project, and you know that anyone with a halo is helping out with AoA. While translations **definitely** help and contribute to AoA as a whole, the translation title is more or less permanent, and I'm not entirely sure if that's something I want to do as of yet. 

I'm definitely not ruling it out, don't worry, but I have some thinking to do :)
I'm also trying to find a better way to track the people who should currently have crowns, as currently I have to manually track down the MC username of every person who should get one, which is a royal pain in the ass
