### ISSUE TITLE
Remove gun recoil

### ISSUE THREAD

**Issue by Lithobraker** [Tslat/Advent-Of-Ascension#946]
In AoA, guns have this recoil mechanic that forces the player's view to move upwards upon firing.
While somewhat realistic, I find it obnoxious most of the time, rather than being an interesting challenge.

It's simple to move your mouse down to compensate for recoil, but people only have so much mousepad available, which makes using high fire rate weapons unnecessarily annoying.

Even FPS games that have visual recoil don't often actually mess with the player's aim, beyond a simple accuracy decrease during extended firing.

I think it would make the gunplay feel a lot smoother and less clunky- recoil might be fine if it happened quickly, with a sudden 'jerk' upwards, but if the current effect is the best implementation possible, I say just remove it entirely.

A lot of what makes a weapon satisfying and fun to use in any game is the sound and the visuals- but while recoil may add some feeling of 'power' to a weapon, this is nothing compared to the audiovisual aspect- and indeed, recoil- especially recoil like this- can make it unsatisfying instead by annoying the player.

While I'm at it, I think replacing gun projectiles with simple glowing line textures like Terraria would make them look a lot better in action! While unrealistic, a lot of players do expect every round to be a tracer round. If such a thing is possible, I believe most people would enjoy that more.

**Comment by Cruuk** [comment]
Ehh, I never really minded the recoil at all, really the culprit here are 5.0 fire rate weapons. I think having more possible ways to balance a weapon is a good thing. The control enchantment reduces recoil, and blasters have no recoil. It's a just a small downside of bullet-damage weapons, it's really the high fire rate ones that are really annoying.

Also, I disagree with the glowing line thing. That would only translate well to MC if the projectile traveled very fast, and projectile speed was not *not easy* to work with at all from what I've heard. Notice how scoped sniper projectiles are invisible? It's impossible for projectile sprites to *visually* travel that fast, so they had to become invisible if we wanted them to keep their extreme speed. Guns shooting these yellow/red lines would just look kind of stupid, and would probably be longer than the actual hitbox, which I would not like at all.

**Comment by Lithobraker** [comment]
> 
> 
> Ehh, I never really minded the recoil at all, really the culprit here are 5.0 fire rate weapons. I think having more possible ways to balance a weapon is a good thing. The control enchantment reduces recoil, and blasters have no recoil. It's a just a small downside of bullet-damage weapons, it's really the high fire rate ones that are really annoying.
> 
> Also, I disagree with the glowing line thing. That would only translate well to MC if the projectile traveled very fast, and projectile speed was not _not easy_ to work with at all from what I've heard. Notice how scoped sniper projectiles are invisible? It's impossible for projectile sprites to _visually_ travel that fast, so they had to become invisible if we wanted them to keep their extreme speed. Guns shooting these yellow/red lines would just look kind of stupid, and would probably be longer than the actual hitbox, which I would not like at all.

That's fair about the glowing lines, and I think I understand what you mean about recoil. That makes sense, though I'd still want high fire-rate weapons to have reduced recoil.
In retrospect, there's nothing really wrong with it on slower weapons, so yeah, you're right.
