### ISSUE TITLE
Make rune pouches great again.

### ISSUE THREAD

**Issue by centhusiastx2** [Tslat/Advent-Of-Ascension#978]
**Describe/name the item/content this suggestion relates to**
I'm fighting Cotton Candor, and runes are piling up my inventory, and by the time he's almost dead, I have no runes left. There's no way that I know of making my inventory larger, and when I use Third Party Mods like Backpacks, and Iron Backpacks, they don't take them from there. They can only take what's in my inventory. I consider this extremely unfair and it needs to be fixed.

**Comment by Cruuk** [comment]
IIRC Staves are all about taking a bit more space with the runes, rune pouch was removed for a reason. It made them a bit busted, barring the nasty skill. It was also just unintuitive for newer players, since the runes didn't actually work outside the pouch.
It's the same reason ammo pouches aren't gonna be a thing. (I think)

Candor's stupid mechanic could just get reworked instead.

**Comment by Seishan123** [comment]
I think it would be a better idea to change Cotton Candor's mechanics if thats the case. I would suggest that the 6 damaging staves are able to affect him at any time, BUT some do more damage to him than others (like a critical hit) which is based on the colours of his 'feet' (if you would call them that). However I would remove the fact that noxious staffs could damage him otherwise he would be too easy.
