### ISSUE TITLE
Hitboxes are too large on most mobs.

### ISSUE THREAD

**Issue by JabZ-TF2** [Tslat/Advent-Of-Ascension#985]
**Mod Version**
What version of the mod are you on?
3.1.2b
**Describe the bug**
The hitboxes of most mobs like the Nightwatcher, Cyclops, Automaton, Dweller, Rock crawler are much larger than their actual model suggests. Either increase the size of their model to fix this or make the hit/attackboxes smaller to fit their model.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a mob
2. Get hit from 2 blocks away
3. Die
4. Repeat

**Expected behavior**
You will notice that you are being hit without the mob actually touching you.

**Comment by Cruuk** [comment]
IIRC this is kind of impossible because once the hitbox size hits a certain point, the melee range is always 1 block minimum, and it can't be reduced unless you reduce the actual hitbox itself, but then it would be smaller than the model itself.

Also, is the hitbox of those particular mobs really that big? I have had 0 trouble with those mobs using a sword. Keep in mind the range of a sword is like 3.5 blocks, maybe you're just standing too close. Stuff like Horndron is what has the problematic hitboxes, and I tried to make a solution for those ones. https://github.com/Tslat/Advent-Of-Ascension/issues/846

**Comment by Tslat** [comment]
Most of your complaints smell of 1.7.10.
Show me some specific examples of how the hitbox is wrong plz
